### ISSUE TITLE
onPlayerMove getFromChunk and getToChunk

### ISSUE THREAD

**Issue by mani1232** [PaperMC/Folia#100]
### Expected behavior

I expected to get coordinates from chunk to chunk

### Observed/Actual behavior

From Chunk return null

### Steps/models to reproduce

in event onPlayerMove try to get from chunk and to chunk

### Plugin and Datapack List

![image](https://github.com/PaperMC/Folia/assets/70480001/5fe17b25-d083-4c38-8d24-36eb192b8df2)

### Folia version

![image](https://github.com/PaperMC/Folia/assets/70480001/dde5515f-5fe1-406f-8774-453ef5bea2d6)

**Comment by Spottedleaf** [comment]
I don't understand
