### ISSUE TITLE
1.20.1 | Server Crash

### ISSUE THREAD

**Issue by ImNotSoftik** [PaperMC/Folia#101]
### Stack trace

```
[paste your stack trace or a paste.gg link here!](https://paste.gg/p/anonymous/d80c1290e4bc419e9342701f4874185c)
```

### Plugin and Datapack List

![image](https://github.com/PaperMC/Folia/assets/78680226/72f189dd-0734-4070-97c2-94e187539277)

### Actions to reproduce (if known)

I do not know what it is, but the server often crashes because of it

### Folia version

![image](https://github.com/PaperMC/Folia/assets/78680226/142332a9-031b-42ac-bdd4-d935c9241c15)

This Folia fork

### Other

I do not know what it is, but the server often crashes because of it

**Comment by kugge** [comment]
Please don't report Kaiiju crashes on Folia tracker. + That log is a crash that occurred on `git-Paper-45`

**Comment by LucidAPs** [comment]
Strange, I had the same crash but with paper.
https://nekobin.com/davabijuqo
