### ISSUE TITLE
Portal Damage

### ISSUE THREAD

**Issue by ImNotSoftik** [PaperMC/Folia#102]
### Expected behavior

https://medal.tv/games/minecraft/clips/1bJQaiVyOSMep2/d1337SMY4Bzd?invite=cr-MSxwQUIsMTg3MTY5MDgxLA

### Observed/Actual behavior

https://medal.tv/games/minecraft/clips/1bJQaiVyOSMep2/d1337SMY4Bzd?invite=cr-MSxwQUIsMTg3MTY5MDgxLA

### Steps/models to reproduce

https://medal.tv/games/minecraft/clips/1bJQaiVyOSMep2/d1337SMY4Bzd?invite=cr-MSxwQUIsMTg3MTY5MDgxLA

### Plugin and Datapack List

no

### Folia version

latest

**Comment by DoctaEnkoda** [comment]
The video is 25 days old, don't you have a recent one?

**Comment by f3f5-dev** [comment]
> The video is 25 days old, don't you have a recent one?

same issues for 25.06.2023

**Comment by ImNotSoftik** [comment]
> The video is 25 days old, don't you have a recent one?

This is not my video, but it happened on my server. I looked on one discord server for mentions of it and found this video there and just added it here

**Comment by ImNotSoftik** [comment]
cause nocheatplus
