### ISSUE TITLE
Desync Problem

### ISSUE THREAD

**Issue by kolderz** [PaperMC/Folia#107]
### Expected behavior

The player position should sync correctly,

### Observed/Actual behavior

The player position isn't synced correctly. You can't punch or do anything outside of the range.

### Steps/models to reproduce

Need 2 players to join the server and the player will be desync

### Plugin and Datapack List

A clean world with No plugins or Datapacks

### Folia version

This server is running Folia version git-Folia-"801cff1" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 801cff1)
You are running the latest version

### Other

![image](https://github.com/PaperMC/Folia/assets/10612667/590a86eb-ecce-4764-84fa-bd819259dde1)
![image](https://github.com/PaperMC/Folia/assets/10612667/9b4412cc-409a-4b9f-9127-0232811d045e)

**Comment by Spottedleaf** [comment]
Can't produce, need steps
