### ISSUE TITLE
MSPT 1000+, 100% util, 20TPS, cannot login

### ISSUE THREAD

**Issue by cgw2023** [PaperMC/Folia#108]
### Expected behavior

players can login

### Observed/Actual behavior

players cannot login, /tps show 100% util , mspt 1000+ and 20TPS for certain region
players inside the region (if they have already login before this problem happened) cannot leave the region, cannot interact with the region's block(break no drop item), is like the server is lagging, but server list show that they are online, commands can affect them but cannot teleport them away from the region

![image](https://github.com/PaperMC/Folia/assets/136877036/cc6f9012-3567-4f91-a81e-ae6ea9df2dc8)

![image](https://github.com/PaperMC/Folia/assets/136877036/2105de4f-ed47-4ba7-a074-e005d0a184f8)

player outside of the region can play normally

### Steps/models to reproduce

unknown

### Plugin and Datapack List

[20:34:05 INFO]: Server Plugins (32):
[20:34:05 INFO]: Bukkit Plugins:
[20:34:05 INFO]:  - AnnouncerPlus, AntiPopup, Attollo, BetterRTP, BlockLocker, BlueMap, Chunky, ChunkyBorder, CMILib, CodFrame
[20:34:05 INFO]:  CoreProtect, DiscordSRV, DragonDropElytra, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, FancyNpcs, GreenChunk
[20:34:05 INFO]:  GSit, HeadDrop, LuckPerms, Matrix, PlaceholderAPI, ProtocolLib, Residence, ShulkerRespawner, TAB-Bridge, Vault
[20:34:05 INFO]:  ViaBackwards, ViaVersion

### Folia version

[20:34:19 INFO]: This server is running Folia version git-Folia-19 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 34039e3 on HEAD)
You are -14 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Folia-"fa018cc" (MC: 1.20.1)

### Other

https://paste.denizenscript.com/View/111703

**Comment by PedroMPagani** [comment]
Try to reproduce the issue without any plugins and using the latest folia version

**Comment by kugge** [comment]
Please send a spark profiler report, there is no context at all

**Comment by cgw2023** [comment]
> Please send a spark profiler report, there is no context at all & the /version is sus

where can I get folia version of spark?

**Comment by DoctaEnkoda** [comment]
> > Please send a spark profiler report, there is no context at all & the /version is sus
> 
> where can I get folia version of spark?

https://github.com/lucko/spark/pull/312#issuecomment-1605946962

**Comment by f3f5-dev** [comment]
> > > Please send a spark profiler report, there is no context at all & the /version is sus
> > 
> > 
> > where can I get folia version of spark?
> 
> [lucko/spark#312 (comment)](https://github.com/lucko/spark/pull/312#issuecomment-1605946962)

not working currently for 1.20.1

**Comment by kugge** [comment]
> > > > Please send a spark profiler report, there is no context at all & the /version is sus
> > > 
> > > 
> > > where can I get folia version of spark?
> > 
> > 
> > [lucko/spark#312 (comment)](https://github.com/lucko/spark/pull/312#issuecomment-1605946962)
> 
> not working currently for 1.20.1

You can compile this :

https://github.com/kugge/spark/tree/feat/folia

If the jar above don't work.

**Comment by ImNotSoftik** [comment]
> > > > > Please send a spark profiler report, there is no context at all & the /version is sus
> > > > 
> > > > 
> > > > where can I get folia version of spark?
> > > 
> > > 
> > > [lucko/spark#312 (comment)](https://github.com/lucko/spark/pull/312#issuecomment-1605946962)
> > 
> > 
> > not working currently for 1.20.1
> 
> You can compile this :
> 
> https://github.com/kugge/spark/tree/feat/folia
> 
> If the jar above don't work.

Your jar doesn't work either

**Comment by cgw2023** [comment]
seems like is a problem caused by residence https://github.com/Folium-MC/Residence-Maven/issues/7
however, the author of this fork version don't know how to solve it
Also no one can confirm whether this is a bug from here. But some of the error message do say it is caused by residence.

**Comment by kugge** [comment]
> > > > > > Please send a spark profiler report, there is no context at all & the /version is sus
> > > > > 
> > > > > 
> > > > > where can I get folia version of spark?
> > > > 
> > > > 
> > > > [lucko/spark#312 (comment)](https://github.com/lucko/spark/pull/312#issuecomment-1605946962)
> > > 
> > > 
> > > not working currently for 1.20.1
> > 
> > 
> > You can compile this :
> > https://github.com/kugge/spark/tree/feat/folia
> > If the jar above don't work.
> 
> Your jar doesn't work either

It works. Just pick the right jar..

**Comment by colinpapa** [comment]
> 似乎是由居住[Folium-MC / Residence-Maven#7](https://github.com/Folium-MC/Residence-Maven/issues/7)引起的问题，但是，这个分叉版本的作者不知道如何解决它也没有人可以确认这是否是这里的错误。但一些错误消息确实说这是由居住引起的。

Not only is the problem of the residential plug-in, even if I remove the residential plug-in, the problem still exists, and the error is found that there may be a problem with the protoclib plug-in

**Comment by cgw2023** [comment]
problem seems solved with new version of plugin, I do not see such error now
