### ISSUE TITLE
Teleport to another world

### ISSUE THREAD

**Issue by KonusIntelliJ** [PaperMC/Folia#113]
### Is your feature request related to a problem?

When we can teleport player to another world (location) without crash?

### Describe the solution you'd like.

none

### Describe alternatives you've considered.

none

**Comment by Spottedleaf** [comment]
Please re-open this issue with more details, including the crash logs.

**Comment by KonusIntelliJ** [comment]
Oh, sorry, i had older folia and i have a crash server when teleport player to another world, now i tried, allright work.
