### ISSUE TITLE
No spigot /restart

### ISSUE THREAD

**Issue by ewof** [PaperMC/Folia#116]
### Expected behavior

I do `/restart` and if `settings.restart-script` in `spigot.yml` has a valid script, it runs the script

### Observed/Actual behavior

```
> restart
[19:38:15 INFO]: Unknown command. Type "/help" for help.
```

### Steps/models to reproduce

Make folia server
Do /restart

### Plugin and Datapack List

None

### Folia version

```
> version
[19:38:55 INFO]: Checking version, please wait...
[19:38:55 INFO]: This server is running Folia version git-Folia-"801cff1" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 801cff1)
You are 5 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Folia-"34039e3" (MC: 1.20.1)
```

**Comment by ewof** [comment]
yea this says `/reload` is disabled i'm talking about `/restart`

**Comment by JacktheDevel0per** [comment]
I get that data packs won't really work, but why is /ride disabled? seems like the approach to folia could be flawed? can Players ride things? if so, does the command system run on a thread that can't ask other threads to do things?

**Comment by electronicboy** [comment]
Commands which mutate world state need to be updated to mutate world state correctly for the barriers

**Comment by JacktheDevel0per** [comment]
so it is a TODO not a won't work

**Comment by ocelotpotpie** [comment]
/restart isn't on the roadmap for Folia. That might change someday in the future but for now closing this as not planned/won't fix.
