### ISSUE TITLE
Create and load custom world

### ISSUE THREAD

**Issue by KonusIntelliJ** [PaperMC/Folia#118]
### Is your feature request related to a problem?

How can i create and load own custom world. Bukkit.createWorld(new WorldCreator(CUSTOM_WORLD)) is UnsupportedOperationException
![image](https://github.com/PaperMC/Folia/assets/62984001/6cdbb15e-b7fc-4c80-b9d6-26993c078881)

### Describe the solution you'd like.

-

### Describe alternatives you've considered.

-

**Comment by electronicboy** [comment]
Creating world's is currently unsupported, please read the documentation for this project
