### ISSUE TITLE
keepInventory

### ISSUE THREAD

**Issue by FedericoMurcielago** [PaperMC/Folia#124]
### Expected behavior

Hello, On my paper server in the server.properties configuration file I have keepInventory=true enabled.
and when I die I don't lose the objects I have in my inventory

### Observed/Actual behavior

In this Folia installation, even though in the server.properties configuration file I have keepInventory=true active
When it dies it does not preserve things :(
Do you have any other method to activate this feature?

I would appreciate any help you can give me.

### Steps/models to reproduce

-

### Plugin and Datapack List

nothing
empty
without any plugin

### Folia version

This server is running Folia version git-Folia-"6b978f2" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 6b978f2)
You are running the latest version

**Comment by PancakeTAS** [comment]
I don't think keepInventory ever was a server property to begin with. It's a gamerule so in order to enable it you need the /gamerule command.

**Comment by KonusIntelliJ** [comment]
Not work keep-inventory from code or set value in server.properties, but gamerule is working.

**Comment by Spottedleaf** [comment]
keepInventory is a game rule that must be set for all worlds individually that you want to have it enabled for. You can use the /gamerule command to do this.
