### ISSUE TITLE
Buried Treasure Map Sometimes Turns Into Blank Default Map

### ISSUE THREAD

**Issue by Goro922** [PaperMC/Folia#128]
### Expected behavior

https://youtu.be/UwrGywjQw2Q

### Observed/Actual behavior

https://youtu.be/nKfEST1v1zg

### Steps/models to reproduce

- Open a chest from a shipwreck or any structure that could hold a buried treasure map.
- The server may freeze for 5-10 seconds or for a brief 1 second. During this freeze, the buried treasure map may convert into a blank map. However, sometimes the buried treasure map appears normally.

### Plugin and Datapack List

none

### Folia version

This server is running Folia version git-Folia-"6b978f2" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 6b978f2)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Folia-"ca3b7ad" (MC: 1.19.4)

### Other

The lag only occurs when a chest, containing a buried treasure map, has never been opened. At times, it displays a standard buried treasure map, but often it converts to a blank map labeled as a 'buried treasure map'. Occasionally, opening the chest can cause the server's TPS to drop to 5, before rebounding back to 20 after some time. In other instances, there's only a minor lag and the treasure is converted.

**Comment by Spottedleaf** [comment]
The TPS part is completely expected.

**Comment by Spottedleaf** [comment]
The treasure map will remain blank if the nearest buried treasure structure cannot be found within ~1100 blocks. You need to verify that there are no nearby buried treasures with the locate command.
