### ISSUE TITLE
Music player bug

### ISSUE THREAD

**Issue by GitJhopa** [PaperMC/Folia#136]
### Expected behavior

When I turned on the music record and the players were standing nearby - I killed one of them and he left our chunk, but then I broke the player with music and teleported him to us - his music was still playing, although the player was gone.

### Observed/Actual behavior

When I turned on the music record and the players were standing nearby - I killed one of them and he left our chunk, but then I broke the player with music and teleported him to us - his music was still playing, although the player was gone.

### Steps/models to reproduce

When I turned on the music record and the players were standing nearby - I killed one of them and he left our chunk, but then I broke the player with music and teleported him to us - his music was still playing, although the player was gone.

### Plugin and Datapack List

Clear Folia testing

### Folia version

This server is running Folia version git-Folia-"6b978f2" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 6b978f2)
You are 5 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

**Comment by electronicboy** [comment]
This is how vanilla works, if the player isn't nearby, the jukebox won't
stop the sound for them

**Comment by GitJhopa** [comment]
heh
