### ISSUE TITLE
Error when new player join

### ISSUE THREAD

**Issue by mani1232** [PaperMC/Folia#137]
### Expected behavior

Join player

### Observed/Actual behavior

New player can not log in and in the console very many errors, as well as these errors are not saved in /logs

Only this saved logs
[latest (2).log](https://github.com/PaperMC/Folia/files/12157060/latest.2.log)

### Steps/models to reproduce

I don't know how it happened, but if you delete the broken world then everything works fine (if you run the broken world on paper it works fine)

### Plugin and Datapack List

Tested with and without plugins

### Folia version

Tested with paper, Folia and Kaiju
Works fine only on paper
All cores on latest versions

### Other

Tested with and without pterodactyl
Tested with java 17-20
Tested with and without jvm fags

**Comment by mani1232** [comment]
(World size: 4GB)

**Comment by ocelotpotpie** [comment]
Please reproduce this on Folia and post a log. We do not and will not ever support forks of Folia.

**Comment by mani1232** [comment]
> Please reproduce this on Folia and post a log. We do not and will not ever support forks of Folia.

Yes but im test it with Folia
![image](https://github.com/PaperMC/Folia/assets/70480001/5be515e2-f252-4120-8fc6-a6525beb7673)
![image](https://github.com/PaperMC/Folia/assets/70480001/e240652a-cb6a-4e16-a5ee-cb6455a3fd2f)
![image](https://github.com/PaperMC/Folia/assets/70480001/4f507aa7-f743-45b0-b7b2-6bc2861100b4)

And it dont save logs

**Comment by mani1232** [comment]
Read pls full bugreport
