### ISSUE TITLE
server can't stop

### ISSUE THREAD

**Issue by ytpoma08** [PaperMC/Folia#149]
### Expected behavior

When /reload confirm is entered, the server is reloaded and the server responds.

### Observed/Actual behavior

The server is not responding to all commands.

### Steps/models to reproduce

When /reload confirm is executed, the server responds to some commands sent by the player, but even the stop command does not respond in the bucket console. To shut down the server, you must forcefully shut it down from the scheduler.

### Plugin and Datapack List

nothing

### Folia version

This server is running Folia version git-Folia-"f6e91e9" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f6e91e9)
You are running the latest version

**Comment by Nacioszeczek** [comment]
There's a handful of commands that are disabled on Folia and `reload` is one of those.
You can take a look [here](https://docs.papermc.io/folia/faq#what-commands-does-folia-disable) for the full list.
Additionally, this duplicates #44 and therefore I'll be closing it.
