### ISSUE TITLE
Want Forge

### ISSUE THREAD

**Issue by HiBer2007** [PaperMC/Folia#154]
### Is your feature request related to a problem?

i want run Minecraft server on a old server，but it is too slow to run forge server,but folia is run well on this machine,so i want a core both have folia and forge .

### Describe the solution you'd like.

add forge to folia or create a new core for forge and folia

### Describe alternatives you've considered.

none

**Comment by JRoy** [comment]
no

**Comment by EterNityCH** [comment]
As the Folia readme stated, there will never be a Forge support version. (I am explaining the no JRoy mentioned above as he closed this as I was still typing ._.)

**Comment by veryredpp** [comment]
based
