### ISSUE TITLE
Modding support

### ISSUE THREAD

**Issue by PaulDotSH** [PaperMC/Folia#160]
### Is your feature request related to a problem?

Mods are a huge part of minecraft, mods like create can modify minecraft into a entire new game, having way more content and new experiences.
However since the base minecraft server is singlecore, more than a few players in a complex world is very hard even for the top hardware at the moment.

### Describe the solution you'd like.

Since I know Folia won't support forge (already searched), what about fabric or quilt? Or maybe a custom framework in the future? I am sure any implementation would greatly benefit Folia and that existing framework.

### Describe alternatives you've considered.

There are no multithreaded servers besides folia

**Comment by powercasgamer** [comment]
Folia will not be ported to Fabric nor Forge nor Quilt or any other modding framework.

**Comment by Konpaku-LVX** [comment]
i am extremely curious if a multithreaded server will ever crop up for fabric environments, as they are getting more popular these days in server side only environments.
