### ISSUE TITLE
Size settings for the regions of the Regionizer

### ISSUE THREAD

**Issue by OMNIDROID2995** [PaperMC/Folia#165]
### Is your feature request related to a problem?

New regions are only created after enormous distances between the players. This is not a huge problem, but we host our Minecraft server on an aarch64 (ARM) system. It's not slow, but it's no longer the fastest hardware in terms of single-core performance. There are times when the TPS drops below 15. Until the threshold for a new region is reached, performance problems usually occur beforehand.

### Describe the solution you'd like.

A possibility to tell the Regoinizer via a configuration file approximately from which distance it should open a new region.

### Describe alternatives you've considered.

Unfortunately I have no ideas for alternatives

### Other

Nevertheless, many thanks for this wonderful work

Even with the current state, we have a LOT more performance with Folia than with the stock vanilla server. We will show our appreciation for this at some point ;)

**Comment by ocelotpotpie** [comment]
Configurable minimum regions are not on the roadmap for Folia. If you have a map or use case that would require smaller areas you may want to consider using Paper instead.
