### ISSUE TITLE
Folia Ubuntu builds error

### ISSUE THREAD

**Issue by ObsidianMC123** [PaperMC/Folia#168]
### Expected behavior

it got error when i tried to build

### Observed/Actual behavior

> Task :paper:spigotDecompileJar FAILED
> Task :getPaperUpstreamData FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':paper:spigotDecompileJar'.
> io.papermc.paperweight.PaperweightException: Execution of 'org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler' failed with exit code 137. Log file: /root/folia/Folia/.gradle/caches/paperweight/upstreams/paper/.gradle/caches/paperweight/taskCache/spigotDecompileJar.log Classpath: /root/.gradle/caches/modules-2/files-2.1/io.papermc/patched-spigot-fernflower/0.1+build.6/9b5f78629421668afe04815042180c0b67c30723/patched-spigot-fernflower-0.1+build.6.jar

### Steps/models to reproduce

> Task :paper:spigotDecompileJar FAILED
> Task :getPaperUpstreamData FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':paper:spigotDecompileJar'.
> io.papermc.paperweight.PaperweightException: Execution of 'org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler' failed with exit code 137. Log file: /root/folia/Folia/.gradle/caches/paperweight/upstreams/paper/.gradle/caches/paperweight/taskCache/spigotDecompileJar.log Classpath: /root/.gradle/caches/modules-2/files-2.1/io.papermc/patched-spigot-fernflower/0.1+build.6/9b5f78629421668afe04815042180c0b67c30723/patched-spigot-fernflower-0.1+build.6.jar

### Plugin and Datapack List

none

### Folia version

idk

**Comment by electronicboy** [comment]
`failed with exit code 137`
The process was killed, likely as you ran out of memory or something
