### ISSUE TITLE
Mob spawning issue in world_nether and world_the_end

### ISSUE THREAD

**Issue by roggy666** [PaperMC/Folia#174]
### Expected behavior

Mobs spawn evenly, balanced

### Observed/Actual behavior

When you beat a zombie penlin, an unlimited number of them begin to spawn, since all the zombie piglins begin to run up to you, in the locations where they stood before, new zombie piglins spawn cyclically and run to you

### Steps/models to reproduce

Go the nether in survival mode
Hit the zombified piglin, in open areas 

### Plugin and Datapack List

It can be reproduce without plugins, on the clear folia 

### Folia version

[05:59:49 INFO]: This server is running Folia version git-Folia-"1e5e215" (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 1e5e215)
You are running the latest version

### Other

And I have a lot of endermans in the end, There are especially many of them on farms, where they trigger on the endermite like piglins on the player

![IMG_20231130_060125_084](https://github.com/PaperMC/Folia/assets/59109355/e62f415e-3a3b-4383-9d20-41af85e4f81f)

**Comment by Spottedleaf** [comment]
Can't reproduce
