### ISSUE TITLE
How to load/unload region while the folia server is running

### ISSUE THREAD

**Issue by nyancat-hu** [PaperMC/Folia#175]
### Is your feature request related to a problem?

There are many scenarios, such as incompatible plugins, bugs, etc., that can lead to MSPT 1000+, 100% util in a region. The players within the region are unresponsive.

### Describe the solution you'd like.

Can we detect and unload these abnormal regions in some way to enhance the stability of Folia?

### Describe alternatives you've considered.

An Api or an existing command？

**Comment by Spottedleaf** [comment]
The server needs to be restarted in these cases.

In reality, this only happens due to the lack of a watchdog - which should automatically kill the server and warn when these events are happening.

**Comment by nyancat-hu** [comment]
> The server needs to be restarted in these cases.
> 
> In reality, this only happens due to the lack of a watchdog - which should automatically kill the server and warn when these events are happening.

Is there no other way but to restart?

Imagine other players playing normally, but one or two players getting stuck due to a bug and needing to restart the entire server

**Comment by HyCore** [comment]
I made a workaround for that, I made a script that send a command like /tps in a server running in tmux or docker. And if I don't get an answer, of that a value for the mspt is higher than x amount. Then I kill the server process. (It will look like a little rollback for players, but help in having a resilient server)
