### ISSUE TITLE
How to obtain the real IP address of a client in Folia through proxy protocol v2?

### ISSUE THREAD

**Issue by Yunmoan** [PaperMC/Folia#178]
### Is your feature request related to a problem?

When using some CDNs (TCP load balancers), I need to use the proxy-protocol-v2 protocol to obtain the real IP address of the client during reverse proxying in order to succeed.

### Describe the solution you'd like.

Hopefully, proxy-protocol-v2 compatibility can be achieved through plug-ins or other methods.

### Describe alternatives you've considered.

I tried to enable proxy access and install the solution previously used on the Paper platform (such as using the haproxy-detector plugin), but it didn't work.  The CDN IP address was still obtained

**Comment by rexlManu** [comment]
I think this issue can be closed. `send-proxy-v2` is already supported via paper (and folia) when 'proxy-protocol' is enabled. I also can confirm it via a test setup that it works. 

```
global
    log stdout format raw local0

defaults
    log     global
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend minecraft_front
    bind *:25565 transparent
    mode tcp
    default_backend minecraft_back

backend minecraft_back
    mode tcp
    balance leastconn
    option tcp-check
    server minecraft_server mc:25565 maxconn 32 send-proxy-v2
    ```
    version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      TYPE: "FOLIA"
    volumes:
      - ./data:/data
    networks:
      - haproxy-net
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "25565:25565"
    networks:
      - haproxy-net
    restart: unless-stopped

networks:
  haproxy-net:
    driver: bridge
    ```
