### ISSUE TITLE
Can I restore far lands?

### ISSUE THREAD

**Issue by qihang518887** [PaperMC/Folia#182]
### Is your feature request related to a problem?

Folia seems to be very suitable for loading far lands. But I can't find a teaching mechanism to restore this on it.

### Describe the solution you'd like.

I want to change some code to restore far lands, or even change the location where it appears.

### Describe alternatives you've considered.

I want to use farlandsagain to restore this mechanism, but this plugin does not support folia.

**Comment by Warriorrrr** [comment]
I don't see what folia has to do with the far lands at all? If you want to re-add them you'll be on your own
