### ISSUE TITLE
Problems when building the project

### ISSUE THREAD

**Issue by Alugor** [PaperMC/Folia#19]
### Expected behavior

When building the project I expect to build the executable files in build/libs dir

### Observed/Actual behavior

![image](https://user-images.githubusercontent.com/100799413/229109567-9242bfeb-7c99-4f58-ae78-6bfd52e5aa0b.png)

### Steps/models to reproduce

Cloning the latest repository
running `./gradlew applyPatches`

### Plugin and Datapack List

didn't come there yet

### Folia version

latest commit March 31 around 1:35pm UTC+1

### Other

Since there is no docu how to compile this project I used the one which Folia is forked from
https://github.com/PaperMC/Paper#how-to-compiling-jar-from-source

**Comment by lynxplay** [comment]
Please head to the discord for further help, you are presumably hitting the path limit on windows.
