### ISSUE TITLE
Ignited TNT occasionally cannot be pushed by piston

### ISSUE THREAD

**Issue by cgw2023** [PaperMC/Folia#192]
### Expected behavior

Ignited TNT will be 100% able to be pushed by piston

### Observed/Actual behavior

Some ignited TNT cannot be pushed

### Steps/models to reproduce

1. use piston to push TNT to anti explode area
2. TNT that cannot be pushed successfully will destory the redstone contraptions 
Video
https://youtu.be/-oU9bg7o3S8

### Plugin and Datapack List

Bukkit Plugins:
AnnouncerPlus, AntiPopup, Attollo, AutoTreeChop, AxInventoryRestore, AxShulkers, BetterRTP, BlockLocker, BlueMap, BungeeGuard
Chunky, ChunkyBorder, CMILib, CodFrame, CoreProtect, DecentHolograms, DeluxeMenus, DiscordSRV, DragonDropElytra, Essentials
EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, FancyNpcs, floodgate, FoliaFlow, GreenChunk, GSit, HeadDrop
Kaiivoid, LuckPerms, Matrix, PlaceholderAPI, PlayerWarps, ProtocolLib, Residence, ShulkerRespawner, spark, TAB-Bridge
Vault, ViaBackwards, ViaVersion, VillagerOptimizer, zAuctionHouseV3

### Folia version

This server is running Folia version git-Folia-"3843340" (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 3843340 on dev/1.20.2)

### Other

optimize-explosion have been tested by enable/disable but still the same

**Comment by ocelotpotpie** [comment]
Can you reproduce this without any plugins installed, please?

**Comment by cgw2023** [comment]
unfortunately, yes.

**Comment by Spottedleaf** [comment]
I need a world which showcases the issue so I can produce locally.

**Comment by cgw2023** [comment]
The player that reported this issue gave me this map, which is on 1.20.2.
The machine that shown on the video is here, if the spawn point is wrong, the machine is the one above
https://cdn.discordapp.com/attachments/1201178996767993916/1206811602175655936/TEST.zip?ex=65e69863&is=65d42363&hm=6b8846d792b3ea15acde308d096a31fc689dc0d05f7af25ae9d4f3445a041192&

**Comment by KujouMolean** [comment]
https://github.com/LuminolMC/Luminol/blob/ver/1.20.4/patches/server/0019-Piston-fixes-from-molean-server.patch

this patch fixed this issue

**Comment by Spottedleaf** [comment]
Please try on https://github.com/PaperMC/Folia/commit/e50d09b67b83ea6ca1451d329dd9694cf155c64d

**Comment by Spottedleaf** [comment]
> Please try on [e50d09b](https://github.com/PaperMC/Folia/commit/e50d09b67b83ea6ca1451d329dd9694cf155c64d)

Assuming resolved
