### ISSUE TITLE
Ticking mechanism small issue on schedule end and the values

### ISSUE THREAD

**Issue by PedroMPagani** [PaperMC/Folia#193]
### Expected behavior

Expected behavior for ticking or warning as overloaded?

### Observed/Actual behavior

Currently what's happening is Folia seems to be missing a few ticks ->
### Steps/models to reproduce

no idea how 

### Plugin and Datapack List

none

### Folia version

60b1508

### Other

Is this a configuration problem, is there a specific way to approach this?
threaded-regions:
  threads: 8

(i have 25 regions enabled but most of them are not using a lot of mspt or so)

**Comment by ocelotpotpie** [comment]
What's your output of /version?

If you're running on the master branch you're on 1.20.2, not 1.20.4. You'd want to be on the most recent build to test any issues/bugs.

**Comment by PedroMPagani** [comment]
Does the region scheduling work based on the global executor and or so how is the scheduling of the regions like activity or inactivity, that might be how the task is getting scheduled, I am running a small custom version that only changes the Async event where i'm passing some data, I can implement debugs to look at the issue further just lmk if you have anything in mind.

(1.20.4 is not the master, I know i'm on 1.20.2)

**Comment by PedroMPagani** [comment]
I kind of added a debug here:
(scheduledEnd-startTime)
for the times it does not tick the problem is -4396147
values are getting to be negative

**Comment by PedroMPagani** [comment]
final long scheduledStart = this.getScheduledStart();
final long scheduledEnd = scheduledStart + TIME_BETWEEN_TICKS;

private long scheduledStart = DEADLINE_NOT_SET;
public static final long DEADLINE_NOT_SET = Long.MIN_VALUE;

**Comment by PedroMPagani** [comment]
the issue is parkNanos on the mechanism of the ticking scheduler.

**Comment by PedroMPagani** [comment]
here are my debugs from prod:

[13:12:15] [Region Scheduler Thread #4/INFO]: [STDOUT] [ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner] disable 3 for 26.812526 took 139.299752 1533645036816609

[13:12:15] [Region Scheduler Thread #4/INFO]: [STDOUT] [ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner] break 3 on 1533645037444055

![image](https://github.com/PaperMC/Folia/assets/56891617/0ed4db93-ebb8-452e-8b73-a37355ccaffe)

**Comment by PedroMPagani** [comment]
[19:29:57 INFO]: This server is running Folia version git-Folia-"60b1508" (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 60b1508)

output of /version (there's some local git commits i did so probably will not really match with the master) - none of the commits touch any region ticking.

**Comment by PedroMPagani** [comment]
For knowledge this issue turned out to be two things:
- Overloaded system which caused the #parkNanos to wake up after the long diff, causing the tick to endup running a "long" time later and then not completing the wanted 20tps.
- After also switching to a low latency kernel this helped a bit, as well as fixing some small thread switching overhead also helped. (This is nice and should probably be in the readme too - overallocating threads wil lcause tps issues due to overloading the JVM).
