### ISSUE TITLE
Players unable to join after a while

### ISSUE THREAD

**Issue by Netherwhal** [PaperMC/Folia#200]
### Expected behavior

Players are able to join

### Observed/Actual behavior

After running Folia on `8939611bb53d6d1d98fd76e91c320d55a28700ad` for a couple of hours (varies), players are unable to join. Either stuck in "Encrypting" or "Joining world" screen until connection times-out.

No Exceptions / No Errors. But logs are full of:

```
[12:38:44] [Region Scheduler Thread #4/INFO]: Foobar (/xxx:20758) lost connection: Disconnected
[12:38:51] [User Authenticator #90/INFO]: UUID of player Foobar is 1efb7ece-
[12:38:54] [Region Scheduler Thread #3/INFO]: Foobar (/xxx:20823) lost connection: Disconnected
```

**Switching to `7bc26ecc74fed21699033d5e7ed5d003796b60cf` resolves the issue for now, but I need more days to confirm.**

### Steps/models to reproduce

Unfortunately I do not have a way to reproduce. On Test-servers everything works fine. Only with "real" load the issue occurs. It seems like having less plugins installed increases the time until the issue occurs, but even with zero plugins, the issue still happens.

### Plugin and Datapack List

This is an issue with no plugins installed

### Folia version

`8939611bb53d6d1d98fd76e91c320d55a28700ad`

### Other

Tried Java 17 and 21 with various args, removing jmx, adding Velocity in-front - nothing helped except rolling back.

**Comment by Spottedleaf** [comment]
https://github.com/PaperMC/Folia/commit/e22501a8e39b8f234bfbedbe0560b6f8f425a818
