### ISSUE TITLE
Alternative event for EntityPortalEvent?

### ISSUE THREAD

**Issue by nyancat-hu** [PaperMC/Folia#207]
### Expected behavior

Players keep raising animals in the  world and using portal teleportation to bypass the maximum number of animals in the chunk. This allows for unlimited spawning of animals, causing server lag. I want to ban some animals from teleporting through portal, but in reality,EntityPortalEvent does not work!!!
I want to prevent some entities from entering the portal

### Observed/Actual behavior

EntityPortalEvent does not work  in Folia
I want an alternative solution

### Steps/models to reproduce

	@EventHandler
	public void onEntityPortal(EntityPortalEvent e) {
		System.out.println("test1");
		List<String> currentList = PortalLimiter.getInstance().getConfig().getStringList("allow-type");
		if (!currentList.contains(e.getEntityType().toString())) {
			System.out.println("test2");
			e.setCancelled(true);
		}
	}

### Plugin and Datapack List

[18:36:25 INFO]: Server Plugins (1):
[18:36:25 INFO]: Bukkit Plugins:
[18:36:25 INFO]:  - PortalLimiter
> datapack list
[18:36:33 INFO]: Unknown command. Type "/help" for help.

### Folia version

> version
[18:35:48 INFO]: This server is running Folia version git-Folia-"b2306ae" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b2306ae)

**Comment by nyancat-hu** [comment]
> There have already been discussions for a solution for this which involves a new event system concept which has already been discussed and is part of the todo list formulation.

Thank you, I will wait for the new event system. But is there an alternative solution before that? As long as entities can be restricted from passing through the portal, any method is possible

**Comment by electronicboy** [comment]
if you just want to prevent entities from portaling in general, can't you just use the enter portal event?

**Comment by electronicboy** [comment]
oh, that's not cancellable; not sure what the best approach here would be

**Comment by AllenLinong** [comment]
> 哦，那是不能取消的;不确定这里最好的方法是什么

EntityPortalLock
