### ISSUE TITLE
Unable to initialize main class

### ISSUE THREAD

**Issue by Justman100** [PaperMC/Folia#213]
### Expected behavior

Running server

### Observed/Actual behavior

> Error: Unable to initialize main class org.bukkit.craftbukkit.Main
Caused by: java.lang.NoClassDefFoundError: joptsimple/OptionException

### Steps/models to reproduce

```bash
git init
git pull https://github.com/PaperMC/Folia
bash gradlew publishToMavenLocal
```

### Plugin and Datapack List

*Could not be compiled*

### Folia version

SNAPSHOT

**Comment by powercasgamer** [comment]
Follow the build steps on Paper's [README](https://github.com/papermc/paper?tab=readme-ov-file#how-to-compiling-jar-from-source)

**Comment by Justman100** [comment]
> Follow the build steps on Paper's [README](https://github.com/papermc/paper?tab=readme-ov-file#how-to-compiling-jar-from-source)

Ah, working! Thanks 🙂

**Comment by Justman100** [comment]
Had used the wrong .jars 🤣
