### ISSUE TITLE
big ender_chest

### ISSUE THREAD

**Issue by bilwjjsai0093** [PaperMC/Folia#215]
### Is your feature request related to a problem?

My server is bungeecord, the core used by server 1 is purpur, server 2 is folia, I have enabled the big ender_chest feature in purpur, but my sync plugin gets an error message ender_chest the size should be 27, but the incoming data is 54

### Describe the solution you'd like.

If you can, I'd like to add settings to enable the big ender_chest

### Describe alternatives you've considered.

I thought about adding an extra ender chest plugin, but it not very good

**Comment by bilwjjsai0093** [comment]
![image](https://github.com/PaperMC/Folia/assets/120778827/5de1648d-7a11-4f90-9fb9-13c6aea1e06d)

**Comment by electronicboy** [comment]
There is generally little interest on our part in breaking vanilla compatibility, and such a feature would not belong in folia anyways
