### ISSUE TITLE
Version 1.20.6

### ISSUE THREAD

**Issue by StateException** [PaperMC/Folia#223]
### Is your feature request related to a problem?

Release 1.21 coming soon

### Describe the solution you'd like.

Version 1.20.6

### Describe alternatives you've considered.

No

### Other

Hello, could you please update Folia to version 1.20.6? There is a little less than a month left until update 1.21 and I would like to get the latest version 1.20. I saw that it is already in the dev branch, but not sure if I can use this version. Do you have any TODO, what is ready in the dev branch and what is not? Maybe we can provide you with any assistance?

I understand that this is a rather painstaking work that requires time and effort, and I’m probably not the first person to ask for this, but still... Thank you in advance

Regards!

**Comment by CodeByCam** [comment]
Updates to Folia do not have any sort of estimate for when they release, ever. Any and all updates will arrive when they are ready, and the only thing to do is wait for them patiently along with everyone else. You can keep an eye our on Paper's [Forum](https://forums.papermc.io/), and [Discord](https://discord.gg/papermc) announcement channels for updates.

**Comment by MidnightTale** [comment]
Best way you can just try and see dev branch, test, and report issues, developers will know what left, of the current state is not ready production for use as they said there no eta.
