### ISSUE TITLE
PlayerRespawnEvent, PlayerPostRespawnEvent not trigger

### ISSUE THREAD

**Issue by MidnightTale** [PaperMC/Folia#229]
### Expected behavior

![image](https://github.com/PaperMC/Folia/assets/125941391/45d2335e-da99-4473-84b7-e2d83c8075d2)

on paper
This server is running Paper version 1.20.6-115-master@9d6f2cc (2024-05-28T14:55:16Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.20.6-DEV-78f49e0 (MC: 1.20.6)

### Observed/Actual behavior

![image](https://github.com/PaperMC/Folia/assets/125941391/84f592bd-1290-4559-8d2b-723a3edc2243)
didn't see PlayerRespawnEvent, PlayerPostRespawnEvent trigger

### Steps/models to reproduce

use api PlayerRespawnEvent, PlayerPostRespawnEvent
![image](https://github.com/PaperMC/Folia/assets/125941391/526b7e8c-e0b8-4d7b-bffe-b4b91e8d0b8b)

### Plugin and Datapack List

no datapack

plugin list
[20:50:48 INFO]: Server Plugins (2):
[20:50:48 INFO]: Bukkit Plugins:
[20:50:48 INFO]:  - extendertool, Haste4Everyone

### Folia version

This server is running Folia version 1.20.6-DEV-HEAD@78f49e0 (2024-05-22T19:56:09Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
Error obtaining version information
Previous version: 1.20.6-115-9d6f2cc (MC: 1.20.6)

**Comment by electronicboy** [comment]
This is covered in the documentation

**Comment by quiquelhappy** [comment]
> This is covered in the documentation

I have not seen a mention of this anywhere. Could you please share it?
