### ISSUE TITLE
Tamed mobs don't teleport to their owner at great distance (across region?)

### ISSUE THREAD

**Issue by iLemon** [PaperMC/Folia#236]
### Expected behavior

Tamed mobs such as wolves should teleport to their owner when their owner teleports or flies away and lands at a distance.

### Observed/Actual behavior

Tamed mobs do not teleport across long distances (presumably across Folia regions)

### Steps/models to reproduce

Steps with random example coordinates:
- `/tp iLemon 2000 100 2000`
- Spawn a Wolf with a wolf spawn egg
- Tame Wolf with bone
- `/tp iLemon 20000 100 20000`
- Land on ground, walk around, etc.
- Wolf doesn't teleport to you
- Go back to `/tp iLemon 2000 100 2000`
- Wolf is still at original location

### Plugin and Datapack List

None (tested on empty server)

### Folia version

> ver
[17:30:30 INFO]: Checking version, please wait...
[17:30:31 INFO]: This server is running Folia version 1.20.6-DEV-master@36e5e83 (2024-06-13T16:25:28Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version

### Other

Have had this issue for a while, back on 1.20.4 builds too.

**Comment by Warriorrrr** [comment]
This is normal minecraft behaviour, once after you teleport the chunks you were in will unload/no longer be ticked, which prevents the wolf from teleporting to you. Once another player causes the chunk to tick again it will teleport like normal.
