### ISSUE TITLE
1.21 update?

### ISSUE THREAD

**Issue by tjw123-tjw** [PaperMC/Folia#240]
### Is your feature request related to a problem?

have 1.21 updated?

### Describe the solution you'd like.

update 1.21

### Describe alternatives you've considered.

i dont know sorry.
and i dont speak english so if you dont mean my idea,i'm sorry.
thanks and please :) 
(@_@）

**Comment by PedroMPagani** [comment]
Close the issue, this is not happening any time soon paper is still working on it.

**Comment by tjw123-tjw** [comment]
ok thanks bro
