### ISSUE TITLE
minecraft.world.entity.animal.Bee$BeeGoToHiveGoal.tick()

### ISSUE THREAD

**Issue by mddewittjr** [PaperMC/Folia#243]
### Stack trace

https://paste.gg/p/anonymous/dbddd2a74a454583b92841c0266fa35a

### Plugin and Datapack List

Chunky

### Actions to reproduce (if known)

Its random, but always the same error PID

### Folia version

1.20.6

**Comment by PedroMPagani** [comment]
Ask your host provider to run a memtest in your ram, you likely have a faulty one.

**Comment by electronicboy** [comment]
the thing accessed illegal memory inside of code that the JVM has compiled, general, update java/use the LTS/check memory

**Comment by mddewittjr** [comment]
gotcha, i will do that.  Thanks
