### ISSUE TITLE
Release 1.21 and make update faster!

### ISSUE THREAD

**Issue by DoNotSMP** [PaperMC/Folia#252]
### Is your feature request related to a problem?

When is Folia 1.21 estimated to release??! Seems like it's a DEAD project. Paper was updated months ago but Folia is unable to catch up! Maybe Folia 1.21 will come after 1.22? 
Also, new implementation, ShreddedPaper already works better!!! How come??? Better multithreading, huge performance boost even for small worlds without "YoU nEED 128 CORES TO RUN IT" crap! 
Sadly, Paper rewrote 50% of the server again just for the sake of it so ShreddedPaper needs to do massive update too.
Anyway, currently it seems that Folia is unmaintainable. Only one person understands what is going on here and obviously that doesn't help at all. DonutSMP can not update to 1.21 because of it! This is unacceptable and very bad for minecraft community.

### Describe the solution you'd like.

Stop rewriting the whole game just because you don't understand vanilla code! 

### Describe alternatives you've considered.

Use https://github.com/MultiPaper/ShreddedPaper

**Comment by PedroMPagani** [comment]
Can you stop?

**Comment by Nacioszeczek** [comment]
We don't provide any estimates on updates because people who work on the project work on it on their own free time. We also provide no warranty for any of our software.

Folia is still experimental so there should be no expectation of updates or stability.

**Comment by DoNotSMP** [comment]
> Can you stop?

Are you okay? There is 0 communication from developers about FOLIA! Nothing! No mention about solving current issues, no future plans, paper discord is just "don't ask this, don't ask that, we don't know anything because we don't understand how folia works" LOL! How can this be a public project? Just hide it!

**Comment by PedroMPagani** [comment]
> Are you okay? There is 0 communication from developers about FOLIA! Nothing! No mention about solving current issues, no future plans, paper discord is just "don't ask this, don't ask that, we don't know anything because we don't understand how folia works" LOL! How can this be a public project? Just hide it!

show your true face, add me on discord pedrojava

**Comment by ShayBox** [comment]
Folia is not production software, it's basically a single person personal project, there's no guaranteed updates, no support, and no official builds. If you want it updated, update it yourself, or wait.

If a server uses Folia such as 2B2T or DonutSMP it's their choice to use software which may never get updated again, they are able to update and build it themselves.
