### ISSUE TITLE
Invisible and frozen players

### ISSUE THREAD

**Issue by Trard** [PaperMC/Folia#256]
### Observed/Actual behavior

Invisible and frozen players

### Steps to Reproduce

- Run Folia 1.21 (61dcc07) without any plugins.
- Run Velocity (3.3.0-SNAPSHOT-413) with only the [tcpshield](https://github.com/TCPShield/RealIP) plugin.
- Join with a tcpshield protected domain via velocity.

I can't give my players the direct ip, so it's the minimal setup.

[Video Demonstration](https://youtu.be/7nUHzfhuekk)

### Plugin and Datapack List

None

### Folia version

61dcc07

**Comment by Spottedleaf** [comment]
https://github.com/PaperMC/Folia/commit/dafae4f54ad783b33ae60caa5919a5eccf40f930
