### ISSUE TITLE
[CRASH] folia 1.21 - server crashing when 350+ bots came out at once

### ISSUE THREAD

**Issue by kitovoi111** [PaperMC/Folia#258]
### Stack trace

```
https://mclo.gs/8jBvH6y or https://paste.gg/p/anonymous/adca91c1f59d411a95ca1b514edeea74
```

### Plugin and Datapack List

spark-1.10.60-bukkit.jar

### Actions to reproduce (if known)

When I launched about 350+ bots and suddenly closed the application with bots, they all suddenly left the server and the server turned off and crashed. 15 threads were allocated and the map was 50,000x50,000. The rule /gamerule spawnRadius 50000 was used.

### Folia version

folia-bundler-1.21-R0.1-SNAPSHOT-reobf.jar

**Comment by ocelotpotpie** [comment]
Should be fixed in the most recent commit.

https://github.com/PaperMC/Folia/commit/2b8c8798972a8393914027c45e544dd997375807
