### ISSUE TITLE
Stopped the server on Folia 1.21

### ISSUE THREAD

**Issue by TATA82** [PaperMC/Folia#260]
### Stack trace

```
https://paste.gg/p/anonymous/1ce0ae5effd64dc2abda2911d05b07cf
```

### Plugin and Datapack List

![image](https://github.com/user-attachments/assets/c07ef29e-8298-45ae-95ed-7a4e136e3625)

### Folia version

![image](https://github.com/user-attachments/assets/edc59d78-2315-4351-8a96-49796a8379da)

### Other

Stopped the server on Folia 1.21

**Comment by APOgamer** [comment]
me too, think its because its still on development and the recipes are bugged

**Comment by TATA82** [comment]
It's still happening https://github.com/PaperMC/Folia/commit/9203a7a887eecdccb93a96ca460ce13364842884
