### ISSUE TITLE
Memory leak on Folia 1.21-2b8c879

### ISSUE THREAD

**Issue by MineSunshineone** [PaperMC/Folia#261]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
Another Fork https://spark.lucko.me/SnZ2v6VqBq （Run 13h）
Folia https://spark.lucko.me/0IPMgOFZdp （Run 10m）
Folia https://spark.lucko.me/tPQbINjmur （Run 20m)
Folia https://spark.lucko.me/v8nIIqWVGB (Run 30m)

### Plugin and Datapack List

> plugins
[11:42:20 INFO]: Server Plugins (36):
[11:42:20 INFO]: Paper Plugins:
[11:42:20 INFO]:  - MiraiMC
[11:42:20 INFO]: Bukkit Plugins:
[11:42:20 INFO]:  - ajLeaderboards, AntiPopup, ArmorStandEditor, AxInventoryRestore, BetterGUI, ChestProtect, Chunky, CommandWhitelist, CoreProtect, CreeperConfetti
[11:42:20 INFO]:  DeathMessage, Essentials, GSit, ICTTools, InvSeePlusPlus, Kaiivoid, KissKiss, LuckPerms, LushRewards, Matrix
[11:42:20 INFO]:  MinePay, NoFlightInEnd, PlaceholderAPI, ProtocolLib, SkullPlugin, spark, TAB-Bridge, ToolStats, TrChat, UseTranslatedNames
[11:42:20 INFO]:  voicechat, Whitelist4QQ, WorldEdit, ZAutoBroadcast, ZeroshiftFcmd

### Actions to reproduce (if known)

Run Folia 1.21-2b8c879

### Folia version

> version
[11:44:06 INFO]: This server is running Folia version 1.21-DEV-dev/1.21@2b8c879 (2024-08-05T03:04:53Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-DEV-2541ddf (MC: 1.21)

### Other

Memory leaks occur approximately every 10 minutes on Folia 1.21-2b8c879
At first I used a Fork of Folia, and the memory leaked. I tried switching to Folia, and the same problem still occurred.

**Comment by RitaSister** [comment]
I can confirm this too, because this is very strange vioalitons old object. My spark: https://spark.lucko.me/yxaIfmfKol

**Comment by RitaSister** [comment]
heap summary too: https://spark.lucko.me/V7xqMTzAZQ

**Comment by MineSunshineone** [comment]
![image](https://github.com/user-attachments/assets/11da85c1-64cc-4137-9014-d3abd6975a69)
maybe cause by spark

**Comment by VaultSmallBoy** [comment]
I played in this server, and I would like to provide more information on the player side.

As we observed, The server will need to run for more than six(6) hours to present a sudden TPS drop (as low as <1.5). For players in the server, the TPS would drop to 1~2 for few seconds, then backs to normal(~19.5 TPS) for around 15 seconds, and repeats the malfunction. As about 15 minutes pass, the frequency of this malfunction becomes higher and the normal TPS time shortens to about 5 seconds. During this time, the Server Health Report (runned by command /tps) showed ambiguous data. Everytime when we run it during the low TPS time, it reported different high-utilization regions. However, in the past ~5 hours, everything worked normally with not even one suspicious TPS drop.

**Comment by ranminecraft** [comment]
same issue

**Comment by electronicboy** [comment]
you haven't ran save-off have you? otherwise, something is keeping millions of entity instances around, would really need to see a heap dump to see where it's coming from, not that I can offer much

**Comment by RitaSister** [comment]
> you haven't ran save-off have you? otherwise, something is keeping millions of entity instances around, would really need to see a heap dump to see where it's coming from, not that I can offer much

I think nobody run /save-off. On my server only /save-on always

**Comment by MrHua269** [comment]
Stress tested by using https://github.com/PureGero/minecraft-stress-test/ on the latest version but cannot reproduce.
Stress tester start commandline: java -Dbot.count=200 -Dbot.ip=127.0.0.1 -Dbot.port=18750 -Dbot.login.delay.ms=5000 -Dbot.radius=10000 -jar minecraft-stress-test-1.0.0-SNAPSHOT-jar-with-dependencies.jar
Plugins:
![cec95e67adfd644c7da0b284f488bcf8](https://github.com/user-attachments/assets/1e7f5489-8f3f-4d76-a87d-e1a626500116)
Server start commandline: ./zulu22.30.13-ca-jdk22.0.1-linux_x64/bin/java -Xmx100G -Xms100G -XX:+UnlockDiagnosticVMOptions -XX:+UnlockExperimentalVMOptions -XX:+HeapDumpOnOutOfMemoryError -XX:+UseLargePages -XX:LargePageSizeInBytes=2M -XX:+UseShenandoahGC -XX:-ShenandoahPacing -XX:+ParallelRefProcEnabled -XX:ShenandoahGCHeuristics=adaptive -XX:ShenandoahInitFreeThreshold=55 -XX:ShenandoahGarbageThreshold=30 -XX:ShenandoahMinFreeThreshold=20 -XX:ShenandoahAllocSpikeFactor=10 -Dchunky.maxWorkingCount=1000 -javaagent:authlib-injector-1.2.5.jar=https://littleskin.cn/api/yggdrasil -server -agentpath:/home/mrhua269/jprofiler14/bin/linux-x64/libjprofilerti.so=port=8849,nowait --add-modules=jdk.incubator.vector -jar luminol-paperclip-1.21.1-R0.1-SNAPSHOT-mojmap.jar nogui
(Spark was fully disabled by using https://github.com/LuminolMC/Luminol/blob/dev/1.21.1/patches/server/0023-Force-disable-builtin-spark-plugin.patch)

**Comment by Technicolor-creamsicle** [comment]
> > you haven't ran save-off have you? otherwise, something is keeping millions of entity instances around, would really need to see a heap dump to see where it's coming from, not that I can offer much
> 
> 
> 
> I think nobody run /save-off. On my server only /save-on always

Someone will always use a command if it's available. For example `save-off` and `save-on` during backups makes sure that the server does not make any changes to whats going in the backup while it is being done.

**Comment by Euphillya** [comment]
> Stress tested by using https://github.com/PureGero/minecraft-stress-test/ on the latest version but cannot reproduce. Stress tester start commandline: java -Dbot.count=200 -Dbot.ip=127.0.0.1 -Dbot.port=18750 -Dbot.login.delay.ms=5000 -Dbot.radius=10000 -jar minecraft-stress-test-1.0.0-SNAPSHOT-jar-with-dependencies.jar Plugins: ![cec95e67adfd644c7da0b284f488bcf8](https://private-user-images.githubusercontent.com/79621885/356532197-1e7f5489-8f3f-4d76-a87d-e1a626500116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMDQ3MDUsIm5iZiI6MTcyMzIwNDQwNSwicGF0aCI6Ii83OTYyMTg4NS8zNTY1MzIxOTctMWU3ZjU0ODktOGYzZi00ZDc2LWE4N2QtZTFhNjI2NTAwMTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDExNTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMWI0MjEyOTFlMDYxMTI0OGE3MTQ3NmM4OTc5Njc0OGFiYWQ5YjFkOGE3MDljMzVlOTJlMTZjODUzNGQ1OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6XF5oXn_KizvF3QmY01hNbJ9RuaeacNnaRcjRZLk5PE) Server start commandline: ./zulu22.30.13-ca-jdk22.0.1-linux_x64/bin/java -Xmx100G -Xms100G -XX:+UnlockDiagnosticVMOptions -XX:+UnlockExperimentalVMOptions -XX:+HeapDumpOnOutOfMemoryError -XX:+UseLargePages -XX:LargePageSizeInBytes=2M -XX:+UseShenandoahGC -XX:-ShenandoahPacing -XX:+ParallelRefProcEnabled -XX:ShenandoahGCHeuristics=adaptive -XX:ShenandoahInitFreeThreshold=55 -XX:ShenandoahGarbageThreshold=30 -XX:ShenandoahMinFreeThreshold=20 -XX:ShenandoahAllocSpikeFactor=10 -Dchunky.maxWorkingCount=1000 -javaagent:authlib-injector-1.2.5.jar=https://littleskin.cn/api/yggdrasil -server -agentpath:/home/mrhua269/jprofiler14/bin/linux-x64/libjprofilerti.so=port=8849,nowait --add-modules=jdk.incubator.vector -jar luminol-paperclip-1.21.1-R0.1-SNAPSHOT-mojmap.jar nogui (Spark was fully disabled by using https://github.com/LuminolMC/Luminol/blob/dev/1.21.1/patches/server/0023-Force-disable-builtin-spark-plugin.patch)

You’re using a fork of Folia, it would be necessary to retest on a Folia server.

**Comment by MineSunshineone** [comment]
I ran the heap dump file with eclipse and this is the report generated
[heap-2024-08-06_08.06.19_Leak_Suspects.zip](https://github.com/user-attachments/files/16568523/heap-2024-08-06_08.06.19_Leak_Suspects.zip)
![image](https://github.com/user-attachments/assets/2578e60c-ad17-49eb-8a0f-2a1185cc31f6)

**Comment by xymb-endcrystalme** [comment]
```One instance of me.lucko.spark.common.SparkPlatform loaded by org.bukkit.plugin.java.PluginClassLoader @ 0x22b4fbfe848 occupies 23,189,898,336 (32.88%) bytes. The memory is accumulated in one instance of java.lang.Object[], loaded by <system class loader>, which occupies 23,189,861,312 (32.88%) bytes.```

22GB by Spark, huh?
Go to `plugins/spark/config.json` and change `backgroundProfiler` to `false`.

**Comment by MrHua269** [comment]
> `One instance of me.lucko.spark.common.SparkPlatform loaded by org.bukkit.plugin.java.PluginClassLoader @ 0x22b4fbfe848 occupies 23,189,898,336 (32.88%) bytes. The memory is accumulated in one instance of java.lang.Object[], loaded by <system class loader>, which occupies 23,189,861,312 (32.88%) bytes.`
> 
> 22GB by Spark, huh? Go to `plugins/spark/config.json` and change `backgroundProfiler` to `false`.

I tried, but seems it is still leaking

**Comment by xymb-endcrystalme** [comment]
What if you remove spark completely?

**Comment by MineSunshineone** [comment]
> https://github.com/LuminolMC/Luminol/blob/dev/1.21.1/patches/server/0023-Force-disable-builtin-spark-plugin.patch)

 https://github.com/LuminolMC/Luminol/blob/dev/1.21.1/patches/server/0023-Force-disable-builtin-spark-plugin.patch)

**Comment by xymb-endcrystalme** [comment]
https://github.com/PaperMC/Folia/blob/dev/1.21.1/patches/server/0018-Disable-spark-profiler.patch

**Comment by MrHua269** [comment]
> What if you remove spark completely?

Yeah

**Comment by electronicboy** [comment]
@MineSunshineone Leak suspect reports are generally useless, but, the spark plugin you've got installed is eating like 22G of ram

**Comment by MineSunshineone** [comment]
> @MineSunshineone Leak suspect reports are generally useless, but, the spark plugin you've got installed is eating like 22G of ram

I know this. When I saw this report, I removed Spark and started the second test. There was still a memory leak. I guess it was because I didn’t completely remove the built-in Spark.

**Comment by Potenza7** [comment]
Same issue If the server is up for a long time. TPS drops suddenly, usually around 5. It recovers after 10 seconds and then drops suddenly again. This problem does not get fixed until you restart the server. When you look at /tps, it shows meaningless values.

**Comment by PedroMPagani** [comment]
if anyone is interested:
https://github.com/PaperMC/Folia/issues/283 here's the cause.
