### ISSUE TITLE
Folia 1.21 - Server crash when potion effects attempt to access raid instances

### ISSUE THREAD

**Issue by Potenza7** [PaperMC/Folia#264]
### Stack trace

```
paste your stack trace or a paste.gg link here!
```
https://mclo.gs/BdH3c7Z

### Plugin and Datapack List

![image](https://github.com/user-attachments/assets/f4624c39-9da4-447d-bcd3-76a2946afbdb)

### Actions to reproduce (if known)

The server crashes every time the player enters the bug and logs in to the server.

### Folia version

![image](https://github.com/user-attachments/assets/9197815c-2c13-43b2-9af9-993255238b24)

**Comment by Potenza7** [comment]
The previous folia version appears on Mclogs, but after the crash, I updated it to the latest folia version and the same situation still occurs. The player was forced to change his account.

**Comment by Potenza7** [comment]
https://mclo.gs/W7vfQJ0

The player got into a bug again and the server crashed when he entered the server. The player had to create a new account.

**Comment by Spottedleaf** [comment]
https://github.com/PaperMC/Folia/commit/88e0907cadf2358e1d3e06222c0a97722ca4ce12
