### ISSUE TITLE
glow item frame invisible after 1.21 folia restart server

### ISSUE THREAD

**Issue by guojiaqiang123** [PaperMC/Folia#266]
### Expected behavior

Fix bugs

### Observed/Actual behavior

https://github.com/user-attachments/assets/ab1b876b-3926-4790-af0b-c841ad81b165

### Steps/models to reproduce

This server is running Folia version 1.21-DEV-dev/1.21@61dcc07 (2024-08-01T02:15:43Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

This is the version I use

### Plugin and Datapack List

![QQ_1722918312828](https://github.com/user-attachments/assets/a01d024a-6630-485b-ae7d-3a501513d39e)

### Folia version

Folia version 1.21-DEV-dev

**Comment by Kadeluxe** [comment]
Plugin issue?

**Comment by guojiaqiang123** [comment]
Sorry, I updated the latest version of folia-1.21 and the display was restored, not a plugin issue

**Comment by guojiaqiang123** [comment]
Sorry, I updated the latest version of folia-1.21 and the display was restored, not a plugin issue

**Comment by xymb-endcrystalme** [comment]
I'm unable to reproduce the issue on newest Folia.

**Comment by Spottedleaf** [comment]
I cannot produce this on 1.21.4.
