### ISSUE TITLE
Arrmor trims not working

### ISSUE THREAD

**Issue by Macialowskyyy** [PaperMC/Folia#267]
### Expected behavior

Applying trim to the armor

### Observed/Actual behavior

The trim pattern does not apply to the armor, as a result it takes away the trim and the armor remains default

### Steps/models to reproduce

A simple attempt at applying trim to the armor

### Plugin and Datapack List

 Server Plugins (16):
Paper Plugins:
  - FancyHolograms
 Bukkit Plugins:
  - Chunky, Essentials, JBWM-Plots, JbwmLib, JbwmShop, LuckPerms, Matrix, PlaceholderAPI, ProtocolLib, Survival
  Vault, ViaBackwards, ViaVersion, WorldEdit, WorldGuard

### Folia version

Checking version, please wait...
This server is running Folia version 1.20.6-DEV-master@36e5e83 (2024-08-03T12:57:10Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

**Comment by Macialowskyyy** [comment]
Bump

**Comment by Spottedleaf** [comment]
This works for me on 1.21.4. If this still happens, please provide a video so I can look at reproducing the issue.
