### ISSUE TITLE
Writable books don't turn into Written books

### ISSUE THREAD

**Issue by kugge** [PaperMC/Folia#27]
### Expected behavior

After signing a `writable_book`, it should turn into a `written_book`.

### Observed/Actual behavior

`writable_book` don't turn into a `written_book` when signed.

### Steps/models to reproduce

1- Take a `writable_book`
2- Write "a"
3- Click on "Sign"
4- Title = "a"
5- Click on "Sign and close"

### Plugin and Datapack List

```
> plugins
[16:39:02 INFO]: Server Plugins (0):
```

### Folia version

```
> version
[16:38:34 INFO]: This server is running Folia version git-Folia-"7072994" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 7072994)
You are running the latest version
Previous version: git-Folia-"ed7a5c5" (MC: 1.19.4)
```

### Other

When logging out, everything written on the `writable_book` disappear. Same steps as above, but don't sign the book. Log out and log back.
Works fine with `git-Paper-"1704bf7"`

**Comment by Spottedleaf** [comment]
```
            this.filterTextPacket((List) list).thenAcceptAsync(consumer, this.server);
```

Yet another case of completablefuture swallowing exceptions.
