### ISSUE TITLE
Update FOLIA 1.21.1 and FIX BUGS

### ISSUE THREAD

**Issue by DonaldSMP** [PaperMC/Folia#272]
### Is your feature request related to a problem?

1.21.1 update is needed ASAP! Hopefully it won't require another chunk rewrite 50K lines patch and 32 more cores minimal requirement.
Also open issues need a FIX, such as raid / ender dragon crash and memory leaks. 
Please clarify whether we should expect 1.21.1 FOLIA at all or not.

### Describe the solution you'd like.

Solution is to release working 1.21.1 Folia without bugs and memory leaks. 

### Describe alternatives you've considered.

ShreddedPaper but it's not updated to 1.21 yet because Paper rewrite internals every update.

**Comment by kennytv** [comment]
So many woos, so little yeahs
