### ISSUE TITLE
1.21.1 server crash.

### ISSUE THREAD

**Issue by Potenza7** [PaperMC/Folia#275]
### Stack trace

```
paste your stack trace or a paste.gg link here!
https://mclo.gs/XTdEwoV
```

### Plugin and Datapack List

![image](https://github.com/user-attachments/assets/ed4adee1-62ad-4561-87f7-868e41221a4e)

### Folia version

![image](https://github.com/user-attachments/assets/6e058be5-deba-4add-a500-8102a0c0548b)

**Comment by Potenza7** [comment]
> Is this a full error?

Yes

**Comment by sub-kek** [comment]
This is caused by some plugin on your server.
Perhaps should add a check that the world is null and have the method behave differently.

```java
    // Paper start - more teleport API / async chunk API
    @Override
    public java.util.concurrent.CompletableFuture<Boolean> teleportAsync(final Location location, final TeleportCause cause, final io.papermc.paper.entity.TeleportFlag... teleportFlags) {
        Preconditions.checkArgument(location != null, "location");
        location.checkFinite();
        Location locationClone = location.clone(); // clone so we don't need to worry about mutations after this call.

        // Folia start - region threading
        java.util.concurrent.CompletableFuture<Boolean> ret = new java.util.concurrent.CompletableFuture<>();
        java.util.function.Consumer<Entity> run = (Entity nmsEntity) -> {
            boolean success = nmsEntity.teleportAsync(
                ((CraftWorld)locationClone.getWorld()).getHandle(), // NullPointerException at this place because world is null
```

**Comment by Potenza7** [comment]
> This is caused by some plugin on your server. Perhaps should add a check that the world is null and have the method behave differently.
> 
> ```java
>     // Paper start - more teleport API / async chunk API
>     @Override
>     public java.util.concurrent.CompletableFuture<Boolean> teleportAsync(final Location location, final TeleportCause cause, final io.papermc.paper.entity.TeleportFlag... teleportFlags) {
>         Preconditions.checkArgument(location != null, "location");
>         location.checkFinite();
>         Location locationClone = location.clone(); // clone so we don't need to worry about mutations after this call.
> 
>         // Folia start - region threading
>         java.util.concurrent.CompletableFuture<Boolean> ret = new java.util.concurrent.CompletableFuture<>();
>         java.util.function.Consumer<Entity> run = (Entity nmsEntity) -> {
>             boolean success = nmsEntity.teleportAsync(
>                 ((CraftWorld)locationClone.getWorld()).getHandle(), // NullPointerException at this place because world is null
> ```

I found the problem, yes there is more than this log. It is caused by the BadOmen effect. This error and crash still continues in version 1.21.1.
#264  #268

**Comment by sub-kek** [comment]
> I found the problem, yes there is more than this log. It is caused by the BadOmen effect. This error and crash still continues in version 1.21.1.
#264 #268

I doubt it's because of vanilla mechanics. Specifically here the call happens on the API.

**Comment by Potenza7** [comment]
> > I found the problem, yes there is more than this log. It is caused by the BadOmen effect. This error and crash still continues in version 1.21.1.
> > #264 #268
> 
> I doubt it's because of vanilla mechanics. Specifically here the call happens on the API.

Check the logs on the number I tagged. The log here is misleading. It comes entirely from badomen.

**Comment by Potenza7** [comment]
If you clear the player's effect with the /effect clear command, you will get rid of this crash. You must do this very quickly when the player enters the server.

**Comment by Spottedleaf** [comment]
This is definitely plugin related, we do not call teleportAsync. I will look at #264 separately.
