### ISSUE TITLE
Dimension delivery issues

### ISSUE THREAD

**Issue by jasonchaes** [PaperMC/Folia#279]
### Expected behavior

As of 1.21, ender pearls can be teleported to each other in other dimensions, such as when the player is in the Nether and the Overworld has a pearl to teleport, they can be teleported directly, and they will work in the same way in the End

### Observed/Actual behavior

As of 1.21, ender pearls can be teleported to each other in other dimensions, such as when the player is in the Nether and the Overworld has a pearl to teleport, they can be teleported directly, and they will work in the same way in the End

### Steps/models to reproduce

This is in the vanilla version
https://github.com/user-attachments/assets/02928de1-5dca-410b-91dc-2e19d285d746

### Plugin and Datapack List

There are no plugins

### Folia version

1.21

```[tasklist]
### Tasks
```

**Comment by Spottedleaf** [comment]
https://github.com/PaperMC/Folia/commit/99ba4bd7be1ccdfae16198a8cf03b72568828fdf
