### ISSUE TITLE
Blocks on End Portal Obsidian Platform Disappear Instead of Dropping Items When Entering the End

### ISSUE THREAD

**Issue by LaSamubo** [PaperMC/Folia#281]
### Expected behavior

In Minecraft version 1.21 and later, when an entity uses an End Portal to enter the End, blocks placed on the Obsidian Platform should turn into item drops rather than disappearing. This ensures that valuable resources are not lost during the portal transition.

### Observed/Actual behavior

When an entity uses the End Portal to enter the End, blocks placed on the Obsidian Platform directly disappear instead of turning into item drops.

### Steps/models to reproduce

Place blocks on the Obsidian Platform.
Throw an entity (e.g., an apple) through the End Portal from the Overworld to the End.
![2024-08-25_13 25 52](https://github.com/user-attachments/assets/9cb91771-4831-4353-8a9f-f84879b1b978)
![2024-08-25_13 33 54](https://github.com/user-attachments/assets/52d35521-66b7-4363-9f4b-23999d4f5159)
![2024-08-25_13 34 50](https://github.com/user-attachments/assets/76b0b154-3a64-4241-a0c2-333ed1fa2b6a)

### Plugin and Datapack List

ViaVersion

### Folia version

This server is running Folia version 1.21.1-DEV-dev/1.21.1@bfa3106 (2024-08-25T05:03:08Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version

**Comment by Warriorrrr** [comment]
This issue is not exclusive to folia and is already tracked in paper [here](https://github.com/PaperMC/Paper/issues/11142).
