### ISSUE TITLE
Strict Thread Safety Checks in Plugin Development

### ISSUE THREAD

**Issue by ghost** [PaperMC/Folia#289]
Is your feature request related to a problem?
Ensuring thread safety is critical, especially to avoid race conditions in multi-threaded environments.

Describe the solution you'd like:
a mode with strict thread checks everywhere, ensuring we are doing things correctly to avoid race conditions. 
For example thread checks EVERYWHERE where cross region access occurs, maybe plugin scanning for non thread-safe collections (silly idea maybe), stuff like that.

**Comment by Spottedleaf** [comment]
The thread checks in Folia are pretty aggressive and are enabled by default. If you think there are any that are missed, you can open an issue and I can look at it.

There's not really anything I can do about plugin development beyond that.
