### ISSUE TITLE
Entities going through portails lose their weapon

### ISSUE THREAD

**Issue by kugge** [PaperMC/Folia#29]
### Expected behavior

Push a mob with a weapon through a portal, on the other side of the portal it is the same entity with the same weapon.

### Observed/Actual behavior

Push a mob with a weapon through a portal, on the other side of the portal it is the same entity **but without weapon**, and **persistent**.

### Steps/models to reproduce

1- Build a nether portal
2- Summon a zombified piglin with a sword `/summon zombified_piglin`
3- Push it through the portal
4- Zombified piglin is now persistent and without its sword.

### Plugin and Datapack List

None

### Folia version

```
[19:49:33 INFO]: This server is running Folia version git-Folia-"33d2aa8" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 33d2aa8)
You are running the latest version
Previous version: git-Folia-"7072994" (MC: 1.19.4)
```

### Other

This bug seems to make entities persistent
Works with skeletons, wither skeletons...

Works fine on git-Paper-"1704bf7"

**Comment by powercasgamer** [comment]
This also happens with Horses, they keep their saddle but lose armor.

**Comment by Spottedleaf** [comment]
This is due to the removal logic being fired before the entity is copied, as the removal logic wipes the inventory of the entity.

**Comment by R00tB33rMan** [comment]
Did some further testing with this bug: for horses, donkeys, and pigs, this does not appear to affect saddles. It'll just remove horse armor and weapons (or really any sort of armor piece/weapon) on an entity.
