### ISSUE TITLE
Lightning strike ignites entities but not blocks in version 1.21.1

### ISSUE THREAD

**Issue by GarryCZ** [PaperMC/Folia#295]
### Expected behavior

When lightning strikes, it should ignite both entities and the surrounding blocks, as per vanilla Minecraft behavior.

### Observed/Actual behavior

In the version of Folia from [this branch](https://github.com/PaperMC/Folia/tree/dev/1.21.1), lightning successfully ignites entities on hit, but it does not set blocks or the surrounding area on fire as expected.

### Steps/models to reproduce

1. Spawn a lightning bolt either naturally or using the /summon lightning_bolt command or an item that causes lightning (e.g., enchanted trident).
2. Observe that when the lightning hits an entity, the entity is ignited, but no blocks or surrounding area catch fire.

### Plugin and Datapack List

No plugins or datapacks are running on the server.

### Folia version

[15:10:33 INFO]: This server is running Folia version 1.21.1-DEV-dev/1.21.1@88e0907 (2024-10-02T14:21:09Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version

**Comment by Spottedleaf** [comment]
This works for me locally on 1.21.4... I suspect this was due to the early Paper build that Folia 1.21.1 was based on for far too long.
