### ISSUE TITLE
Sand duping not working on Folia 1.21

### ISSUE THREAD

**Issue by QGavoille** [PaperMC/Folia#297]
### Expected behavior

With Paper config unsupported-settings/allow-unsafe-end-portal-teleportation set to true, the gravity blocks duplication via end portal is supposed to work.

### Observed/Actual behavior

No blocks are appearing on the end side when the machine is running, the overworld behavior seems correct.

### Steps/models to reproduce

Build a duper (i used a 10gt for the tests but it should be the same with all types of dupers)
Run it and put a second account on the end side

### Plugin and Datapack List

None

### Folia version

Folia version 1.21.1-DEV-dev/1.21.1@06d719d (2024-10-30T16:02:28Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Other

I tested the same thing on the latest paper version (paper 1.21.1 build 128) and the dupe worked with the exact same configuration.

**Comment by lamlam098** [comment]
same issues on folia 1.21.1 .
bump

**Comment by cgw2023** [comment]
this is correct, when I moved from master 9a19e4286c04bc01b9d7bc005cf66f8cc2dd49ff to dev/1.21.1 06d719d57d7ca9df0bda9f881d330b05aca99ebd the duping does not work.
Not sure which commit caused this problem

**Comment by lamlam098** [comment]
bump

**Comment by Spottedleaf** [comment]
Folia does not allow entities to be ticked after they teleport, which fixes the sand duping. It has to be this way as a removed entity is considered off-region.

**Comment by Panda260** [comment]
so there is no ability to enable sand duping even with plugins?
or another config settings?
`allow-unsafe-end-portal-teleportation: true` does not work
