### ISSUE TITLE
"/execute in minecraft:world" executes the command in all dimensions

### ISSUE THREAD

**Issue by Euphillya** [PaperMC/Folia#300]
### Expected behavior

Hello,

I noticed that we have a problem with the commands that allow us to select the world we want. For example, let's run this command:

``_Euphyllia issued server command: /execute in minecraft:the_nether run kill @e[type=!minecraft:player]``

I'm supposed to kill all entities in the nether world besides the player. But it does it on all worlds.

This happens through the console as well as through the execution of the command by a player.

### Observed/Actual behavior

As I said above, the parameters of the ``/execute in`` command are ignored

### Steps/models to reproduce

Create a server under folia, connect so that entities appear and execute the command.

### Plugin and Datapack List

> plugins
[17:40:27 INFO]: Server Plugins (0):
>
>

### Folia version

```
> version
[17:47:26 INFO]: Checking version, please wait...
[17:47:26 INFO]: This server is running Folia version 1.21.1-DEV-dev/1.21.1@2e7bc07 (2024-11-15T16:45:34Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-DEV-06d719d (MC: 1.21.1)
```

**Comment by Spottedleaf** [comment]
This happens in Vanilla and Paper.

This looks rather intentional, as the entity selector parser will only limit it to the current world context under a few conditions. Your best bet is to report it to Mojang.

**Comment by Euphillya** [comment]
~~This also happens on teleport commands and such. On vanilla it doesn't happen.~~ Mybad, This is a mod that fixed this
