### ISSUE TITLE
[BUG] Wind Charges Work Inconsistently on Folia 1.21.1

### ISSUE THREAD

**Issue by JosTheDude** [PaperMC/Folia#301]
### Expected behavior

Wind Charges work as expected as per vanilla behavior

https://streamable.com/dtefua | Video of Vanilla Behavior

### Observed/Actual behavior

Wind charges have inconsistent behavior (barely ever works, rare proper usage), only working occassionally with seemingly no rhyme or reason.

https://streamable.com/qs3n2i | Video of Behavior

### Steps/models to reproduce

- Obtain Wind Charge Item in Game
- Use Wind Charge

### Plugin and Datapack List

![Image](https://github.com/user-attachments/assets/14099fa0-5a4d-4906-91e9-7812324c484c) | Plugin List

### Folia version

This server is running Folia version 1.21.1-DEV-dev/1.21.1@2e7bc07 (2024-11-26T19:00:15Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-21-cfa3c61 (MC: 1.21.1)

### Other

N/A

**Comment by Euphillya** [comment]
I was unable to reproduce it on my server in 1.21.1 and 1.21.3.

**Comment by Skullians** [comment]
What version of CoreProtect is this? @JosTheDude

**Comment by JosTheDude** [comment]
> I was unable to reproduce it on my server in 1.21.1 and 1.21.3.

Pure vanilla?

**Comment by Spottedleaf** [comment]
I can't produce this locally either on 1.21.4.

**Comment by JosTheDude** [comment]
Will close -- appears to be a setup issue on our end which wasn't confirmed properly. Thank you for the assistance<3
