### ISSUE TITLE
JVM crashes due to native method loading

### ISSUE THREAD

**Issue by Ghost-Kokoro** [PaperMC/Folia#305]
### Stack trace

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fffd4e34e9a, pid=498576, tid=312608
#
# JRE version: OpenJDK Runtime Environment Zulu21.32+17-CA (21.0.2+13) (build 21.0.2+13-LTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu21.32+17-CA (21.0.2+13-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x3e4e9a]
#
# Core dump will be written. Default location: E:\bakamc\test\1.21.1folia\hs_err_pid498576.mdmp
#
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
#
[hs_err_pid498576.log](https://github.com/user-attachments/files/18046342/hs_err_pid498576.log)

### Plugin and Datapack List

Only one plugins which includes native method.

### Actions to reproduce (if known)

Using Zulu21 JVM to start the server and loading any plugins which includes native method.

### Folia version

any version - latest

**Comment by SirYwell** [comment]
1. You seem to be running something that isn't Folia.
2. Your Java version is outdated. Use 21.0.5.
3. Folia doesn't have any effect on how native methods are resolved or executed.

**Comment by Ghost-Kokoro** [comment]
> 1. You seem to be running something that isn't Folia.
> 2. Your Java version is outdated. Use 21.0.5.
> 3. Folia doesn't have any effect on how native methods are resolved or executed.

I'm sure that I'm using Folia. It isn't relevant to what version of Java but server core, cuz I used such JNIC obfuscated plugins on Spigot/Bukkit without any errors.
Only by using Folia can I reproduce the error, one more thing, I can run the same plugin without native obfuscation on Folia correctly.

**Comment by electronicboy** [comment]
Your dump indicates you are using a modified version of folia, which we do not support. Earlier builds of jdk 21 had a bug that would cause jvm crashes when some tooling tries to access jvm internal data.

**Comment by xymb-endcrystalme** [comment]
Liminol != Folia. It's a fork, ask them for support. Who knows what changes they've made.

Windows is a pretty rare deployment OS. Use Linux if you can, it's way more popular. Popular = more chance someone had the same issue as you in the past.

If you have to stay on Windows, try different Java runtimes. Maybe Oracle Java will work? Maybe GraalVM will work?

**Comment by MrHua269** [comment]
> > 1. You seem to be running something that isn't Folia.
> > 2. Your Java version is outdated. Use 21.0.5.
> > 3. Folia doesn't have any effect on how native methods are resolved or executed.
> 
> I'm sure that I'm using Folia. It isn't relevant to what version of Java but server core, cuz I used such JNIC obfuscated plugins on Spigot/Bukkit without any errors.
> Only by using Folia can I reproduce the error, one more thing, I can run the same plugin without native obfuscation on Folia correctly.

It might caused by your plugins which used JNI C.And there is no any native method changes on Luminol

**Comment by Ghost-Kokoro** [comment]
> Liminol != Folia. It's a fork, ask them for support. Who knows what changes they've made.
> 
> Windows is a pretty rare deployment OS. Use Linux if you can, it's way more popular. Popular = more chance someone had the same issue as you in the past.
> 
> If you have to stay on Windows, try different Java runtimes. Maybe Oracle Java will work? Maybe GraalVM will work?

> > > 1. You seem to be running something that isn't Folia.
> > > 2. Your Java version is outdated. Use 21.0.5.
> > > 3. Folia doesn't have any effect on how native methods are resolved or executed.
> > 
> > 
> > I'm sure that I'm using Folia. It isn't relevant to what version of Java but server core, cuz I used such JNIC obfuscated plugins on Spigot/Bukkit without any errors.
> > Only by using Folia can I reproduce the error, one more thing, I can run the same plugin without native obfuscation on Folia correctly.
> 
> It might caused by your plugins which used JNI C.And there is no any native method changes on Luminol

Now it's official version.
[latest.log](https://github.com/user-attachments/files/18048687/latest.log)
[hs_err_pid31704.log](https://github.com/user-attachments/files/18048735/hs_err_pid31704.log)

We have tested java 17-21, which is Oracle version, and they still failed.

**Comment by electronicboy** [comment]
Folia makes 0 changes that would break native library loading; some native library called into the JVM internals which blew up, but there is no information on what it did to trigger that, and folia doesn't make any changes relating to natives afaik, nor is that version of folia supported, so, even if there was a breakage, it would not be fixed

**Comment by MrHua269** [comment]
> > Liminol != Folia. It's a fork, ask them for support. Who knows what changes they've made.
> > 
> > Windows is a pretty rare deployment OS. Use Linux if you can, it's way more popular. Popular = more chance someone had the same issue as you in the past.
> > 
> > If you have to stay on Windows, try different Java runtimes. Maybe Oracle Java will work? Maybe GraalVM will work?
> 
> > > > 1. You seem to be running something that isn't Folia.
> > > > 2. Your Java version is outdated. Use 21.0.5.
> > > > 3. Folia doesn't have any effect on how native methods are resolved or executed.
> > > 
> > > 
> > > I'm sure that I'm using Folia. It isn't relevant to what version of Java but server core, cuz I used such JNIC obfuscated plugins on Spigot/Bukkit without any errors.
> > > Only by using Folia can I reproduce the error, one more thing, I can run the same plugin without native obfuscation on Folia correctly.
> > 
> > It might caused by your plugins which used JNI C.And there is no any native method changes on Luminol
> 
> Now it's official version.
> [latest.log](https://github.com/user-attachments/files/18048687/latest.log)
> [hs_err_pid31704.log](https://github.com/user-attachments/files/18048735/hs_err_pid31704.log)
> 
> We have tested java 17-21, which is Oracle version, and they still failed.

Emmm, Could we talk on QQ?It's unconvenient to discuss a issue that doesn't caused by folia here()

**Comment by Ghost-Kokoro** [comment]
> Folia makes 0 changes that would break native library loading; some native library called into the JVM internals which blew up, but there is no information on what it did to trigger that, and folia doesn't make any changes relating to natives afaik, nor is that version of folia supported, so, even if there was a breakage, it would not be fixed

All right, but the problem only exisiting on Folia, no errors of native method loading were found on Spigot/Bukkit. We have to find another core instead, thank you.

**Comment by xymb-endcrystalme** [comment]
> We have tested java 17-21, which is Oracle version, and they still failed.

As I said, try Linux. Or at least WSL. There is not enough information, it can be pretty much everything. 🤷
Hell, it could even be that RAM is damaged in one specific place that JVM likes or something. I had this happen to my own machine (system almost working, but just crashing on one specific program... just because of how the memory layout happened).

So memtest86 could also be a good idea.

**Comment by Ghost-Kokoro** [comment]
> Emmm, Could we talk on QQ?It's unconvenient to discuss a issue that doesn't caused by folia here()

3058877423

**Comment by Ghost-Kokoro** [comment]
> > We have tested java 17-21, which is Oracle version, and they still failed.
> 
> As I said, try Linux. Or at least WSL. There is not enough information, it can be pretty much everything. 🤷 Hell, it could even be that RAM is damaged in one specific place that JVM likes or something. I had this happen to my own machine (system almost working, but just crashing on one specific program... just because of how the memory layout happened).
> 
> So memtest86 could also be a good idea.

I made a support on Linux, as I compiled .so library in the program. We have just tested it and it still failed.
But thanks for your advice, Im getting to find another core.
