### ISSUE TITLE
When I download and unzip this. then use gradlew build I get empty jar

### ISSUE THREAD

**Issue by ScriptsAndApps** [PaperMC/Folia#34]
### Expected behavior

give me a working jar

### Observed/Actual behavior

gives a jar with only a empty manifest

### Steps/models to reproduce

gives a jar with only a empty manifest

### Plugin and Datapack List

gives a jar with only a empty manifest

### Folia version

gives a jar with only a empty manifest

### Other

Are there files missing? i tried intillij and without. ran all bat files.

How to use and build its nowhere in the readme. what are the steps?

**Comment by Owen1212055** [comment]
Here is not the place for questions like this. Please consult the discord for more information.
