### ISSUE TITLE
Command blocks not working

### ISSUE THREAD

**Issue by misha2play** [PaperMC/Folia#39]
### Expected behavior

\* Set enable-command-block=true in server.properties
Join in the world, then place command block, type some command for example summon minecraft:bee ~ ~5 ~
Set command block properties to repeat; always active

**Command block starts spawning bees**

### Observed/Actual behavior

**Command block does nothing**
output field also not working

### Steps/models to reproduce

\* Set enable-command-block=true in server.properties
Join in the world, then place command block, type some command for example summon minecraft:bee ~ ~5 ~
Set command block properties to repeat; always active

Command block doesn't spawning bees

### Plugin and Datapack List

none

### Folia version

This server is running Folia version git-Folia-"b1c668f" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: b1c668f)
You are running the latest version

### Other

Redstone also doesn't activate command block
It looks like command is just stupidly not processed, also command successfully saved in command block
When i type command in chat it works

**Comment by e-im** [comment]
Command blocks are disabled 

https://github.com/PaperMC/Folia/blob/b1c668f2b9155c213dd28b9ce0cc31c1c24696cc/patches/server/0005-Threaded-Regions.patch#L20597

**Comment by misha2play** [comment]
oh sorry, my failure

**Comment by MrSnowmanASOY** [comment]
is there any way to re-enable them? i know they're unstable but i would like to try some things out to see how broken it actually is

**Comment by EterNityCH** [comment]
No there is not way to enable them. However it is possible to make plugin with same functionality of commend block. That would be the better approach.
