### ISSUE TITLE
Foxes duplicate sweet berries

### ISSUE THREAD

**Issue by jdkeke142** [PaperMC/Folia#41]
### Expected behavior

Foxes should not duplicate sweet berries

[Here is a video that shows how it works on paper](https://youtu.be/CxiDUvDSCWw)

### Observed/Actual behavior

Foxes duplicate sweet berries.

[Here is a video that shows the bug](https://youtu.be/0kWpWMq0tNc)

### Steps/models to reproduce

Putting foxes in an enclosure with sweet berries, the duplication happens almost systematically

### Plugin and Datapack List

The server does not use datapacks or plugins

### Folia version

```This server is running Folia version git-Folia-"41c5548" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 41c5548)```

**Comment by Spottedleaf** [comment]
Unable to produce locally, are you still able to produce this? Also; please verify that the random tick speed is set to 3 via the gamerule command.

**Comment by jdkeke142** [comment]
That's pretty weird because I tried on the latest and even on the version this issue was created and I haven't been able to reproduce it either. Yet I'm sure it was happening and I didn't touched the random tick speed, other people were able to reproduce the bug at the time, maybe they could help?
