### ISSUE TITLE
"java.lang.IllegalStateException: Illegal recursive processTicketUpdates" (already holding ticket lock) during ChunkProvider tick

### ISSUE THREAD

**Issue by SlayorPlayz** [PaperMC/Folia#46]
### Stack trace

https://paste.gg/p/anonymous/034189458a1e4d8c8a2add6e47308dc2

### Plugin and Datapack List

Chunky

However this issue was also occuring without it so...

### Actions to reproduce (if known)

Teleport far out when the server is under heavy load.

### Folia version

[02:05:39 INFO]: This server is running Folia version git-Folia-"41c5548" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 41c5548)
You are running the latest version

**Comment by kugge** [comment]
Might be related to #45 [see this comment for an updated stacktrace](https://github.com/PaperMC/Folia/issues/45#issuecomment-1509818731)

**Comment by Spottedleaf** [comment]
This is a different one, and I don't even see how this one is possible.

**Comment by SlayorPlayz** [comment]
> This is a different one, and I don't even see how this one is possible.

Should I test this on a newer compiled version now?
