### ISSUE TITLE
Stash optimization

### ISSUE THREAD

**Issue by F3F5** [PaperMC/Folia#49]
### Is your feature request related to a problem?
.

### Describe the solution you'd like.
![nbt_deduplication](https://user-images.githubusercontent.com/108226177/232333218-acd65c3c-d25c-44e9-a0c2-e6bdfd68353b.png)

### Describe alternatives you've considered.

https://github.com/xymb-endcrystalme/Kaiiju/commit/3e9cb6ec8dc15ffc9e6f5fa6ea0eed7235ac22de
folia fork with this feature

### Other

.

**Comment by ImNotSoftik** [comment]
There's a problem with the chests in mintcraft. If there are too many of them and they will be filled with resource shulkers, then the server will simply shut down from lack of RAM. Also, the server hangs when loading and unloading chunk, saving the world.

**Comment by kugge** [comment]
I don't think that is Folia goal

If you really want to suggest that feature you should open a feature request / bug report on Paper repo

**Comment by Spottedleaf** [comment]
I will be making no changes to the data format on disk, otherwise worlds from or to Vanilla will not load. I also cannot make changes to how items are stored in memory, even at the NBT level as plugins will use all kinds of hacks to do things. So, I am in a position where I can't work on this.

**Comment by Kumorio-6g6s** [comment]
@Spottedleaf Has anything changed since then? Is it possible to fix the server hang when loading a large number of chests with things with the appearance of Sectorfile?

**Comment by Spottedleaf** [comment]
> @Spottedleaf Has anything changed since then? Is it possible to fix the server hang when loading a large number of chests with things with the appearance of Sectorfile?

No
