### ISSUE TITLE
!!!Server compilation error!!!Not behavior error!!!

### ISSUE THREAD

**Issue by CanmiWu** [PaperMC/Folia#55]
### Expected behavior

I encountered a problem while compiling, but I did not find the free issue publishing entry in the feedback screen, so the following question is about compilation errors.

I followed paperMC's build guidance:
//
 1.To compile Paper, you need JDK 17 and an internet connection.
 2.Clone this repo, run ./gradlew applyPatches, then ./gradlew createReobfBundlerJar from your terminal. You can find the 
    compiled jar in the project root's build/libs directory.
 3.To get a full list of tasks, run ./gradlew tasks.
//

### Observed/Actual behavior

//
 1.To compile Paper, you need JDK 17 and an internet connection.
 2.Clone this repo, run ./gradlew applyPatches, then ./gradlew createReobfBundlerJar from your terminal. You can find the 
    compiled jar in the project root's build/libs directory.
 3.To get a full list of tasks, run ./gradlew tasks.
//

### Steps/models to reproduce

I tried to compile this project and here are the steps I used:
(1)I try to git this porject and gradlew.bat build
Then I found a problem. The compiled Jar file was an empty shell and could not be used.
I searched the encyclopedia for a long time and there was something wrong with my steps.
So here's how I did it the second time：
(1)git this project
(2)build tasks
Then I follow the guidance:
//
 1.To compile Paper, you need JDK 17 and an internet connection.
 2.Clone this repo, run ./gradlew applyPatches, then ./gradlew createReobfBundlerJar from your terminal. You can find the 
    compiled jar in the project root's build/libs directory.
 3.To get a full list of tasks, run ./gradlew tasks.
//
(3)gradlew.bat applyPatches
An error occurred when git reached 44%.
The specific error information is listed below.

### Plugin and Datapack List

C:\File\Desktop\Folia\Folia-bulid-2023.4.23\Folia>gradlew.bat applyPatches
> Task :paper:patchCraftBukkit FAILED
> Task :getPaperUpstreamData FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':paper:patchCraftBukkit'.
> io.papermc.paperweight.PaperweightException: Command finished with 128 exit code: git -c commit.gpgsign=false -c core.safecrlf=false clone --no-hardlinks C:\File\Desktop\Folia\Folia-bulid-2023.4.23\Folia\.gradle\caches\paperweight\upstreams\paper\work\CraftBukkit C:\File\Desktop\Folia\Folia-bulid-2023.4.23\Folia\.gradle\caches\paperweight\upstreams\paper\.gradle\caches\paperweight\taskCache\patchCraftBukkit.repo

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 13s
2 actionable tasks: 2 executed

### Folia version

This is the debug message:
//////////////////////////////
C:\File\Desktop\Folia\Folia-bulid-2023.4.23\Folia>gradlew.bat applyPatches --debug -i
Initialized native services in: C:\Users\Ayaka\.gradle\native
Initialized jansi services in: C:\Users\Ayaka\.gradle\native
Received JVM installation metadata from 'C:\Program Files\BellSoft\LibericaJDK-17': {JAVA_HOME=C:\Program Files\BellSoft\LibericaJDK-17, JAVA_VERSION=17.0.5, JAVA_VENDOR=BellSoft, RUNTIME_NAME=OpenJDK Runtime Environment, RUNTIME_VERSION=17.0.5+8-LTS, VM_NAME=OpenJDK 64-Bit Server VM, VM_VERSION=17.0.5+8-LTS, VM_VENDOR=BellSoft, OS_ARCH=amd64}
The client will now receive all logging from the daemon (pid: 24348). The daemon log file: C:\Users\Ayaka\.gradle\daemon\8.0.2\daemon-24348.out.log
Starting 14th build in daemon [uptime: 51 mins 35.186 secs, performance: 100%, GC rate: 0.00/s, heap usage: 0% of 512 MiB, non-heap usage: 36% of 384 MiB]
Using 16 worker leases.
Watching the file system is configured to be disabled
File system watching is inactive
Starting Build
The configuration detachedConfiguration1 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration detachedConfiguration1 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration detachedConfiguration1 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration detachedConfiguration1 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration classpath is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration classpath is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration classpath is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration classpath is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
Settings evaluated using settings file 'C:\File\Desktop\Folia\Folia-bulid-2023.4.23\Folia\settings.gradle.kts'.
Using local directory build cache for the root build (location = C:\Users\Ayaka\.gradle\caches\build-cache-1, removeUnusedEntriesAfter = 7 days).
Projects loaded. Root project using build file 'C:\File\Desktop\Folia\Folia-bulid-2023.4.23\Folia\build.gradle.kts'.
Included projects: [root project 'folia', project ':folia-api', project ':folia-server']

> Configure project :
Evaluating root project 'folia' using build file 'C:\File\Desktop\Folia\Folia-bulid-2023.4.23\Folia\build.gradle.kts'.
The configuration detachedConfiguration1 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration detachedConfiguration1 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration detachedConfiguration1 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration detachedConfiguration1 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration detachedConfiguration2 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration detachedConfiguration2 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration detachedConfiguration2 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration detachedConfiguration2 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :classpath is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :classpath is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :classpath is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :classpath is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
Build cache key for Kotlin DSL accessors for root project 'folia' is a1f6baf722c0f8281fa5999b184255b4
Skipping Kotlin DSL accessors for root project 'folia' as it is up-to-date.

> Configure project :folia-api
Evaluating project ':folia-api' using build file 'C:\File\Desktop\Folia\Folia-bulid-2023.4.23\Folia\Folia-API\build.gradle'.

> Configure project :folia-server
Evaluating project ':folia-server' using build file 'C:\File\Desktop\Folia\Folia-bulid-2023.4.23\Folia\Folia-Server\build.gradle'.
All projects evaluated.
Task name matched 'applyPatches'
Selected primary task 'applyPatches' from project :
Tasks to be executed: [task ':clonePaperRepo', task ':getPaperUpstreamData', task ':applyApiPatches', task ':applyServerPatches', task ':applyPatches']
Tasks that were excluded: []
Resolve mutations for :clonePaperRepo (Thread[Execution worker,5,main]) started.
:clonePaperRepo (Thread[Execution worker,5,main]) started.

> Task :clonePaperRepo
Caching disabled for task ':clonePaperRepo' because:
  Caching has not been enabled for the task
Task ':clonePaperRepo' is not up-to-date because:
  Task state is not tracked.
Resolve mutations for :getPaperUpstreamData (Thread[Execution worker,5,main]) started.
:getPaperUpstreamData (Thread[Execution worker,5,main]) started.

> Configure project :paper
Evaluating project ':paper' using build file 'C:\File\Desktop\Folia\Folia-bulid-2023.4.23\Folia\.gradle\caches\paperweight\upstreams\paper\build.gradle.kts'.
The configuration detachedConfiguration1 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration detachedConfiguration1 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration detachedConfiguration1 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration detachedConfiguration1 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration detachedConfiguration2 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration detachedConfiguration2 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration detachedConfiguration2 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration detachedConfiguration2 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
Using local directory build cache for build ':paper' (location = C:\Users\Ayaka\.gradle\caches\build-cache-1, removeUnusedEntriesAfter = 7 days).
The configuration :paper:classpath is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :paper:classpath is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :paper:classpath is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :paper:classpath is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
Build cache key for Kotlin DSL accessors for project ':paper' is b4948b41110e407a1022c279a058d8e3
Skipping Kotlin DSL accessors for project ':paper' as it is up-to-date.

> Configure project :paper:paper-api
Evaluating project ':paper:paper-api' using build file 'C:\File\Desktop\Folia\Folia-bulid-2023.4.23\Folia\.gradle\caches\paperweight\upstreams\paper\Paper-API\build.gradle.kts'.
The configuration :paper:paper-api:classpath is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :paper:paper-api:classpath is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :paper:paper-api:classpath is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :paper:paper-api:classpath is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
Build cache key for Kotlin DSL accessors for project ':paper:paper-api' is 3c377051dc897d53caa0bed38926dca8
Skipping Kotlin DSL accessors for project ':paper:paper-api' as it is up-to-date.

> Configure project :paper:paper-mojangapi
Evaluating project ':paper:paper-mojangapi' using build file 'C:\File\Desktop\Folia\Folia-bulid-2023.4.23\Folia\.gradle\caches\paperweight\upstreams\paper\Paper-MojangAPI\build.gradle.kts'.
The configuration :paper:paper-mojangapi:classpath is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :paper:paper-mojangapi:classpath is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :paper:paper-mojangapi:classpath is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :paper:paper-mojangapi:classpath is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
Build cache key for Kotlin DSL accessors for project ':paper:paper-mojangapi' is 3c377051dc897d53caa0bed38926dca8
Skipping Kotlin DSL accessors for project ':paper:paper-mojangapi' as it is up-to-date.

> Configure project :paper:paper-server
Evaluating project ':paper:paper-server' using build file 'C:\File\Desktop\Folia\Folia-bulid-2023.4.23\Folia\.gradle\caches\paperweight\upstreams\paper\Paper-Server\build.gradle'.
Resolve mutations for :paper:initSubmodules (Thread[Execution worker,5,main]) started.
:paper:initSubmodules (Thread[Execution worker,5,main]) started.

> Task :paper:initSubmodules
Caching disabled for task ':paper:initSubmodules' because:
  Caching has not been enabled for the task
Task ':paper:initSubmodules' is not up-to-date because:
  Task state is not tracked.
Resolve mutations for :paper:patchSpigotApiPatches (Thread[Execution worker,5,main]) started.
:paper:patchSpigotApiPatches (Thread[Execution worker,5,main]) started.

> Task :paper:patchSpigotApiPatches UP-TO-DATE
Build cache key for task ':paper:patchSpigotApiPatches' is dfc2f696256a173c0d55cc0058d53b66
Skipping task ':paper:patchSpigotApiPatches' as it is up-to-date.
Resolve mutations for :paper:patchSpigotApi (Thread[Execution worker,5,main]) started.
:paper:patchSpigotApi (Thread[Execution worker Thread 8,5,main]) started.

> Task :paper:patchSpigotApi UP-TO-DATE
Caching disabled for task ':paper:patchSpigotApi' because:
  Caching has not been enabled for the task
Skipping task ':paper:patchSpigotApi' as it is up-to-date.
Resolve mutations for :paper:applyApiPatches (Thread[Execution worker Thread 8,5,main]) started.

> Task :paper:applyApiPatches UP-TO-DATE
Caching disabled for task ':paper:applyApiPatches' because:
  Caching has not been enabled for the task
Skipping task ':paper:applyApiPatches' as it is up-to-date.

> Task :getPaperUpstreamData
Caching disabled for task ':getPaperUpstreamData' because:
  Caching has not been enabled for the task
Task ':getPaperUpstreamData' is not up-to-date because:
  Task state is not tracked.
The configuration detachedConfiguration1 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration detachedConfiguration1 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration detachedConfiguration1 is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration detachedConfiguration1 is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration classpath is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration classpath is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration classpath is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration classpath is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
Task name matched 'prepareForDownstream'
Selected primary task 'prepareForDownstream' from project :
The configuration :paper:decompiler is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :paper:decompiler is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :paper:mainSourceElements is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :paper:paperclip is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :paper:paperclip is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :paper:paramMappings is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :paper:paramMappings is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :paper:remapper is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :paper:remapper is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :paper:spigotDecompiler is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :paper:spigotDecompiler is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :paper:testResultsElementsForTest is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
The configuration :paper:paramMappings is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :paper:paramMappings is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
:paper:applyApiPatches (Thread[included builds,5,main]) started.
Resolve mutations for :paper:downloadMcManifest (Thread[included builds,5,main]) started.
:paper:downloadMcManifest (Thread[included builds,5,main]) started.

> Task :paper:downloadMcManifest
Caching disabled for task ':paper:downloadMcManifest' because:
  Caching has not been enabled for the task
Task ':paper:downloadMcManifest' is not up-to-date because:
  Task state is not tracked.

> Task :paper:downloadMcVersionManifest UP-TO-DATE
Caching disabled for task ':paper:downloadMcVersionManifest' because:
  Caching has not been enabled for the task
Skipping task ':paper:downloadMcVersionManifest' as it is up-to-date.

> Task :paper:downloadServerJar UP-TO-DATE
Caching disabled for task ':paper:downloadServerJar' because:
  Caching has not been enabled for the task
Skipping task ':paper:downloadServerJar' as it is up-to-date.

> Task :paper:extractFromBundler UP-TO-DATE
Build cache key for task ':paper:extractFromBundler' is 70b2db541c3ab2815d42632a6438302c
Skipping task ':paper:extractFromBundler' as it is up-to-date.

> Task :paper:addAdditionalSpigotMappings UP-TO-DATE
Build cache key for task ':paper:addAdditionalSpigotMappings' is 10e20ab27ab34d664db37b1162bf2e3a
Skipping task ':paper:addAdditionalSpigotMappings' as it is up-to-date.

> Task :paper:downloadMappings UP-TO-DATE
Caching disabled for task ':paper:downloadMappings' because:
  Caching has not been enabled for the task
Skipping task ':paper:downloadMappings' as it is up-to-date.

> Task :paper:filterVanillaJar UP-TO-DATE
Build cache key for task ':paper:filterVanillaJar' is 941f7fc1f25138f46576e3b01f3e9ff4
Skipping task ':paper:filterVanillaJar' as it is up-to-date.

> Task :paper:generateMappings UP-TO-DATE
Build cache key for task ':paper:generateMappings' is c66ee2be0875d8b6747bad622ffc77c3
Skipping task ':paper:generateMappings' as it is up-to-date.

> Task :paper:generateSpigotMappings UP-TO-DATE
Build cache key for task ':paper:generateSpigotMappings' is bf3692d34da1c294c2e72801d26087f0
Skipping task ':paper:generateSpigotMappings' as it is up-to-date.
:paper:spigotRemapJar (Thread[Execution worker Thread 13,5,main]) started.

> Task :paper:spigotRemapJar UP-TO-DATE
Build cache key for task ':paper:spigotRemapJar' is 71b5435e86d3f824009a43ffe27d8222
Skipping task ':paper:spigotRemapJar' as it is up-to-date.
Resolve mutations for :paper:cleanupMappings (Thread[Execution worker Thread 13,5,main]) started.
:paper:cleanupMappings (Thread[Execution worker Thread 13,5,main]) started.

> Task :paper:cleanupMappings UP-TO-DATE
Build cache key for task ':paper:cleanupMappings' is b4d1e29bd4d359116a53f8f19df15085
Skipping task ':paper:cleanupMappings' as it is up-to-date.
Resolve mutations for :paper:patchMappings (Thread[Execution worker Thread 13,5,main]) started.
:paper:patchMappings (Thread[Execution worker Thread 13,5,main]) started.

> Task :paper:patchMappings UP-TO-DATE
Build cache key for task ':paper:patchMappings' is 2d2028f5c732cff79fb0a8ff86e07167
Skipping task ':paper:patchMappings' as it is up-to-date.
Resolve mutations for :paper:cleanupSourceMappings (Thread[Execution worker Thread 13,5,main]) started.
:paper:cleanupSourceMappings (Thread[Execution worker Thread 13,5,main]) started.

> Task :paper:cleanupSourceMappings UP-TO-DATE
Build cache key for task ':paper:cleanupSourceMappings' is 178b8889d0eadb1d06834826ad59fc60
Skipping task ':paper:cleanupSourceMappings' as it is up-to-date.
Resolve mutations for :paper:remapJar (Thread[Execution worker Thread 13,5,main]) started.
:paper:remapJar (Thread[Execution worker Thread 13,5,main]) started.

> Task :paper:remapJar UP-TO-DATE
The configuration :paper:remapper is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :paper:remapper is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
Build cache key for task ':paper:remapJar' is d2a019bd3076ceaeb3d9592644305548
Skipping task ':paper:remapJar' as it is up-to-date.
Resolve mutations for :paper:fixJar (Thread[Execution worker Thread 13,5,main]) started.
:paper:fixJar (Thread[Execution worker Thread 13,5,main]) started.

> Task :paper:fixJar UP-TO-DATE
Build cache key for task ':paper:fixJar' is 59163ea9a4ddcfbdd54cd73f6641809c
Skipping task ':paper:fixJar' as it is up-to-date.
Resolve mutations for :paper:patchCraftBukkitPatches (Thread[Execution worker Thread 13,5,main]) started.
:paper:patchCraftBukkitPatches (Thread[Execution worker Thread 13,5,main]) started.

> Task :paper:patchCraftBukkitPatches UP-TO-DATE
Build cache key for task ':paper:patchCraftBukkitPatches' is d9761f01d8f60c739d5f468adc44e586
Skipping task ':paper:patchCraftBukkitPatches' as it is up-to-date.
Resolve mutations for :paper:filterSpigotExcludes (Thread[Execution worker Thread 13,5,main]) started.
:paper:filterSpigotExcludes (Thread[Execution worker Thread 13,5,main]) started.

> Task :paper:filterSpigotExcludes UP-TO-DATE
Build cache key for task ':paper:filterSpigotExcludes' is 9fe4f1280e3d7423b93e017860635ae8
Skipping task ':paper:filterSpigotExcludes' as it is up-to-date.
Resolve mutations for :paper:spigotDecompileJar (Thread[Execution worker Thread 13,5,main]) started.
:paper:spigotDecompileJar (Thread[Execution worker Thread 13,5,main]) started.

> Task :paper:spigotDecompileJar UP-TO-DATE
The configuration :paper:spigotDecompiler is both resolvable and consumable. This is considered a legacy configuration and it will eventually only be possible to be one of these.
The configuration :paper:spigotDecompiler is both consumable and declarable. This combination is incorrect, only one of these flags should be set.
Build cache key for task ':paper:spigotDecompileJar' is 3409a5a97306284a8c9f39bf2efe5023
Skipping task ':paper:spigotDecompileJar' as it is up-to-date.
Resolve mutations for :paper:patchCraftBukkit (Thread[Execution worker Thread 13,5,main]) started.
:paper:patchCraftBukkit (Thread[Execution worker Thread 13,5,main]) started.

> Task :getPaperUpstreamData
Resolve mutations for :paper:downloadMcVersionManifest (Thread[included builds,5,main]) started.
:paper:downloadMcVersionManifest (Thread[included builds,5,main]) started.
Resolve mutations for :paper:downloadServerJar (Thread[included builds,5,main]) started.
:paper:downloadServerJar (Thread[included builds,5,main]) started.
Resolve mutations for :paper:extractFromBundler (Thread[included builds,5,main]) started.
:paper:extractFromBundler (Thread[included builds,5,main]) started.
Resolve mutations for :paper:addAdditionalSpigotMappings (Thread[included builds,5,main]) started.
:paper:addAdditionalSpigotMappings (Thread[included builds,5,main]) started.
Resolve mutations for :paper:downloadMappings (Thread[included builds,5,main]) started.
:paper:downloadMappings (Thread[included builds,5,main]) started.
Resolve mutations for :paper:filterVanillaJar (Thread[included builds,5,main]) started.
:paper:filterVanillaJar (Thread[included builds,5,main]) started.
Resolve mutations for :paper:generateMappings (Thread[included builds,5,main]) started.
:paper:generateMappings (Thread[included builds,5,main]) started.
Resolve mutations for :paper:generateSpigotMappings (Thread[included builds,5,main]) started.
:paper:generateSpigotMappings (Thread[included builds,5,main]) started.
Resolve mutations for :paper:spigotRemapJar (Thread[included builds,5,main]) started.

> Task :paper:patchCraftBukkit FAILED
Caching disabled for task ':paper:patchCraftBukkit' because:
  Caching has not been enabled for the task
Task ':paper:patchCraftBukkit' is not up-to-date because:
  Task has failed previously.

> Task :getPaperUpstreamData FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':paper:patchCraftBukkit'.
> io.papermc.paperweight.PaperweightException: Command finished with 128 exit code: git -c commit.gpgsign=false -c core.safecrlf=false clone --no-hardlinks C:\File\Desktop\Folia\Folia-bulid-2023.4.23\Folia\.gradle\caches\paperweight\upstreams\paper\work\CraftBukkit C:\File\Desktop\Folia\Folia-bulid-2023.4.23\Folia\.gradle\caches\paperweight\upstreams\paper\.gradle\caches\paperweight\taskCache\patchCraftBukkit.repo

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
2 actionable tasks: 2 executed

### Other

I try to use this command.
   gradlew.bat cleanBuildCache

I'm sure it's not my Internet.

**Comment by electronicboy** [comment]
Try using a shorter path or building on WSL, seek support on the discord, we can't diagnose such issues here

**Comment by heapybruh** [comment]
Can confirm, moving the project somewhere else which made the path shorter fixed the issue.
Thanks!

To OP: Try moving your project to Desktop, it should work.
