### ISSUE TITLE
Will Folia release versions (1.16.5/1.17.1) in the future?

### ISSUE THREAD

**Issue by BiliAnyao** [PaperMC/Folia#58]
### Is your feature request related to a problem?

Hello, dear team member of folia!

I am a Minecraft player who has been using your Minecraft 1.19.4 server with enthusiasm and satisfaction. However, some of my friends would like to continue using old Minecraft plugins that are only compatible with Minecraft 1.16.5.

Therefore, I would like to request that folia team could consider releasing a server version that works with Minecraft 1.16.5 in the future, to facilitate those players who wish to use old plugins and enjoy better gaming experience. I understand that this may require time and effort from your team, but if it could be realized, I believe many players would benefit.

If you need any additional information or support from us, please let us know. Thank you again for your contribution and efforts in the Minecraft community, and looking forward to your reply!

### Describe the solution you'd like.

The content above

### Describe alternatives you've considered.

The content above

### Other

The content above

**Comment by kugge** [comment]
Folia is not even compatible with 1.19.4 plugins

**Comment by BiliAnyao** [comment]
> Folia 甚至不兼容 1.19.4 插件

这是个有潜力的服务端,有一些插件已经兼容了

**Comment by electronicboy** [comment]
No, as per the faq, it will not
