### ISSUE TITLE
Cannot move entity off-main

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [PaperMC/Folia#62]
### Stack trace

```
https://paste.ubuntu.com/p/dnGZVGBrfb/
```

### Plugin and Datapack List

plugins:
![image](https://user-images.githubusercontent.com/71379165/234618751-bc3f28f1-0d0f-4a69-b015-26728366e71c.png)

datapacket:
![image](https://user-images.githubusercontent.com/71379165/234618806-f01a925b-7843-4a2d-bf5f-d56f846c9e2e.png)

### Actions to reproduce (if known)

According to the player description, at that time they were just exploring in hell and then the server crashed

### Folia version

[23:06:01 INFO]: This server is running Folia version git-Folia-"b97116b" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: b97116b)
You are running the latest version

**Comment by HyCore** [comment]
i also got that issue

**Comment by Spottedleaf** [comment]
Paste is gone.

**Comment by MineSunshineone** [comment]
fixed in https://github.com/PaperMC/Folia/commit/23b6f9e0efe76505d936146529f7db3478e78ad6

**Comment by xiaoyueyoqwq** [comment]
> fixed in [23b6f9e](https://github.com/PaperMC/Folia/commit/23b6f9e0efe76505d936146529f7db3478e78ad6)

thx bro
