### ISSUE TITLE
Villagers "forgetting jobsite blocks"

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [PaperMC/Folia#64]
### Expected behavior

Villagers became insensitive to their workbenches and sometimes did not take their jobs

### Observed/Actual behavior

They would have picked up work very quickly and moved around the workbench

### Steps/models to reproduce

Just give a villager (with default spawn reason) a job site block and after about 20 minutes it occurs.

### Plugin and Datapack List

plugins:
![image](https://user-images.githubusercontent.com/71379165/235053500-fff310fb-c7cc-4d34-b76b-324f04cbd107.png)

datapackets:
![image](https://user-images.githubusercontent.com/71379165/235053540-49e301fd-04e8-4fba-a3c5-368e17268eb0.png)

### Folia version

This server is running Folia version git-Folia-"b97116b" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: b97116b)
You are running the latest version

### Other

I think this issue is very similar to an open issue on Paper: https://github.com/PaperMC/Paper/issues/9154
And I tried removing all datapackets and plugins for testing, and the results are still :(

**Comment by kugge** [comment]
Can you replicate this on Paper ? If you can replicate the exact same issue on Paper, we should wait for a fix from Paper and update upstream

**Comment by xiaoyueyoqwq** [comment]
> Can you replicate this on Paper ? If you can replicate the exact same issue on Paper, we should wait for a fix from Paper and update upstream

I don't think I can, I didn't have this problem with the server that used Paper before; To add, just now some players found that these villagers have just lost their appearance, and their appearance has changed from professional villagers to unemployed vagrants, and their profession has not changed

**Comment by kugge** [comment]
I can reproduce it on Folia but not on Paper.

**Comment by xiaoyueyoqwq** [comment]
> I can reproduce it on Folia but not on Paper.

So that is a Folia problem right?

**Comment by kugge** [comment]
> > I can reproduce it on Folia but not on Paper.
> 
> So that is a Folia problem right?

Probably but not 100% sure

**Comment by xiaoyueyoqwq** [comment]
> > > I can reproduce it on Folia but not on Paper.
> > 
> > 
> > So that is a Folia problem right?
> 
> Probably but not 100% sure

Do you think it will be difficult to fix it?
