### ISSUE TITLE
ChunkHolder at [x, y] in world 'world' does not exist to untrack chunk 

### ISSUE THREAD

**Issue by kugge** [PaperMC/Folia#71]
### Stack trace

[Paste.gg link](https://paste.gg/p/anonymous/9b95dd9658464edbab74102ff4ff3066)
Server crashed at latest stacktrace.

### Plugin and Datapack List

A simple plugin that use teleportAsync on random coordinates. Used to replicate #45, but ended up with this stacktrace

### Actions to reproduce (if known)

When using teleportAsync a lot of time on unloaded chunks / random coordinates.

### Folia version

[15:54:55 INFO]: Checking version, please wait...
[15:54:56 INFO]: This server is running Folia version git-Folia-"47105ea" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 47105ea)
You are running the latest version

### Other

Might be related to #45.
View distance is 32 (to load a lot of chunks)

**Comment by Spottedleaf** [comment]
Can you re-test this on the latest master?

**Comment by Spottedleaf** [comment]
Likely related to https://github.com/PaperMC/Folia/issues/45
