### ISSUE TITLE
Kick with shulker 

### ISSUE THREAD

**Issue by F3F5** [PaperMC/Folia#75]
### Expected behavior

tested in fork: Kaiiju and Folia, same problem.

### Observed/Actual behavior

https://pastes.dev/CqfoszkNBT

### Steps/models to reproduce

Any action with the shulkers.

### Plugin and Datapack List

i don't have plugins

### Folia version

fea2422e25da3617604e2ac22faad00bc7e7cfed

### Other

.

**Comment by electronicboy** [comment]
Something created an invalid nbt tag

**Comment by F3F5** [comment]
> Something created an invalid nbt tag

this is default shulker without any changes

**Comment by kugge** [comment]
How to reproduce this on a new world ?

**Comment by F3F5** [comment]
> How to reproduce this on a new world ?

shulker full with items. error not a rare but rare, sometimes it may not work

**Comment by ImNotSoftik** [comment]
there's no problem on the last folia

**Comment by Spottedleaf** [comment]
Resolved by https://github.com/PaperMC/Paper/commit/a226f44b452c8c75ca077b492ba4a957629ba489 in 1.20
