### ISSUE TITLE
沙子等受重力物品落到火把等不会变成掉落物

### ISSUE THREAD

**Issue by Xing688** [PaperMC/Folia#79]
### Expected behavior

沙子等落到火把上会变成掉落物

### Observed/Actual behavior

如标题所写，沙子等物品掉落到火把或者半如标题所写，沙子等物品掉落到火砖等上面会直接消失，而不是变成掉落物

### Steps/models to reproduce

随便放一个火把，在火把上方高处放一个沙子让它掉落到火把上

### Plugin and Datapack List

![QQ图片20230520123318](https://github.com/PaperMC/Folia/assets/98017796/f8da5ecb-5c04-49e2-8f91-98d4c063fc3b)

### Folia version

![QQ图片20230520123411](https://github.com/PaperMC/Folia/assets/98017796/df84dfd7-29ef-43aa-9d51-4765771fa4a1)

**Comment by EterNityCH** [comment]
Please reproduce your issue with no plugin installed.

请在未安装插件的情况下嘗試重现您的问题。

This is very likely caused by a plugin not Folia itself.

这很有可能是由插件而非 Folia 本身造成的。

**Comment by Xing688** [comment]
好的，我会尝试

**Comment by Xing688** [comment]
未加插件仍有这个问题

**Comment by MineSunshineone** [comment]
Try the newest ver

**Comment by Xing688** [comment]
问题解决，FallingSnow插件问题
