### ISSUE TITLE
Major API Issue for PlayerJoinEvent

### ISSUE THREAD

**Issue by SlayorPlayz** [PaperMC/Folia#80]
### Stack trace

https://paste.gg/p/anonymous/db8a584ccceb42499608c1e40518dc75

Caused by plugin join event (see below)

### Plugin and Datapack List

My own plugin
![image](https://github.com/PaperMC/Folia/assets/68820364/f823c3f0-3690-422f-8dd6-32d96be52823)

### Folia version

[01:11:05 INFO]: This server is running Folia version git-Folia-"be3c9e5" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: be3c9e5)
You are running the latest version

**Comment by emilyy-dev** [comment]
To prevent a player from joining, cancel/set the appropriate result in the PlayerLoginEvent, Join is too late for preventing it but too early to kick
