### ISSUE TITLE
Mob spawning problem with special chunk structure

### ISSUE THREAD

**Issue by MineSunshineone** [PaperMC/Folia#81]
### Expected behavior

On Paper Slime chunk
![7ASHF( UZ8%FRO644ZG7YJD](https://github.com/PaperMC/Folia/assets/107391209/d65cf740-0562-4331-bf28-a64a2ce5ecc3)
On Paper Swamp chunk
![HUU0MC31@PKZ PCYDQ744G6](https://github.com/PaperMC/Folia/assets/107391209/09a5a839-1d66-4c1e-9adb-16d476541e30)
On Paper Nether Fortress Chunk
![F7I1$({2%7T@)6$LP$K95G0](https://github.com/PaperMC/Folia/assets/107391209/394881bb-2223-470a-bb59-379fb5d59789)

### Observed/Actual behavior

On Folia slime chunk
![SL7I3`ESROSH `VW7$P0A{U](https://github.com/PaperMC/Folia/assets/107391209/d7e57402-f0f2-4334-840f-bd8f5bf80982)
On Folia Swamp chunk
![1~5K%2({%)058UJ~1U_8)%5](https://github.com/PaperMC/Folia/assets/107391209/c3dec499-1250-4eba-aee7-07170cda07ae)
On Folia Nether Fortress Chunk
![V}@}~IM8R9Q VFVEA4U2RKU](https://github.com/PaperMC/Folia/assets/107391209/c1bd1b2b-9c5d-42db-9a8a-34e4724df6ef)

### Steps/models to reproduce

1.Use the latest ver of Folia  a1572f1
2.Find these new chunk structures
3.wait

### Plugin and Datapack List

Plugins:
![UC3J}({{2WQUIBFMMLGA01L](https://github.com/PaperMC/Folia/assets/107391209/1dab3a0d-05b8-4a5c-acb6-00f125e69302)
Datapack:
![_VR26 2 @A2{O99~6S(F5NS](https://github.com/PaperMC/Folia/assets/107391209/5d32012e-510d-4cbe-b707-e021d7fd7a47)

### Folia version

[11:25:14 INFO]: Checking version, please wait...
[11:25:16 INFO]: This server is running Paper version git-Paper-540 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: f9f9079)
You are running the latest version
Previous version: git-Folia-"a1572f1" (MC: 1.19.4)

### Other

In this test, all settings are the same except Folia/Paper

**Comment by Stabrinai** [comment]
在吗，我的服务器也遇到了这个问题，但是不知道怎么解决，可以求教吗…

**Comment by Q2297045667** [comment]
> 我的服务器也遇到了这个问题，但是不知道怎么解决，可以求教吗…

你说中文人家也听不懂

**Comment by EterNityCH** [comment]
请使用ChatGPT或DeepL将您的信息翻译成英文，因为这里的程式员主要使用英语
Please use either ChatGPT or DeepL to translate your message to English as the maintainers largely speaks English here.

https://chat.openai.com
https://www.deepl.com/en/translator

Thank you for understanding!
