### ISSUE TITLE
Create an executable file

### ISSUE THREAD

**Issue by amirzarei007** [PaperMC/Folia#85]
### Is your feature request related to a problem?

My expertise is not kotlin or java, and I can't work with gradle and maven to compile the codes

### Describe the solution you'd like.

If you can, like PaperMC, release the release earlier

### Describe alternatives you've considered.

Or If you can, in the readme or document section, give a guide to compile the codes

### Other

Most likely many people like me have this problem I would really appreciate it if you could give me more advice for compile and installing the program

**Comment by amirzarei007** [comment]
> https://github.com/PaperMC/Paper/blob/master/README.md#how-to-compiling-jar-from-source

For this, you need Linux or another package, because when I run gradlew applyPatches in CMD, it gives me this error

![image](https://github.com/PaperMC/Folia/assets/39042372/375cbaa3-f268-4b44-a61f-c0f1ec5734aa)

**Comment by ocelotpotpie** [comment]
Folia is still in active development and builds are not available yet. There are guidelines to building it but if you need help you’d have to join the Paper Discord. Please do not create Github issues or comments for this kind of support stuff.

I’d recommend joining the Discord and reading the information about Folia there to see if it’s something you’d need or able to use. Someone there might be able to help you with building also.
