### ISSUE TITLE
Add per player spawn mob limit

### ISSUE THREAD

**Issue by mani1232** [PaperMC/Folia#87]
### Is your feature request related to a problem?

The problem is that there is no point in spawning a mob if there is no player near it, also without this patch does not work farms mobs and it seems that there are few mobs around the player

### Describe the solution you'd like.

Add a patch from Paper to spawn mobs per player, not per region

### Describe alternatives you've considered.

nope

```[tasklist]
### Tasks
```

**Comment by Spottedleaf** [comment]
Mobs are not spawned if there are no players nearby.
